# GeographyDivisionSelect
module ActionView
  module Helpers
    class InstanceTag  
      def to_geography_division_select_tag(options, html_options)
        html_options = html_options.stringify_keys
        add_default_name_and_id(html_options)
        get_value = value(object)
        options[:selected] = options.has_key?(:selected) ? options[:selected] : get_value
        content_tag("select", 
          add_options(
            geography_division_options_for_select(options), options, get_value
          ), html_options
        )
      end
    end
    class FormBuilder
      def geography_division_select(method, options = {}, html_options = {})
        @template.geography_division_select(@object_name, method, options.merge(:object => @object), html_options)
      end
    end 
    
    module FormOptionsHelper
        # Return select and the options tags based on conditions applied
        # Allowed Types
        # Region - To print the Regions i.e. Continents of the World. Supported are Africa, Asia, Australia, Europe, North America, South America
        # Country - To print All the Countries of the World. Currently we have supported all the 237 countries in the world.
        # State - To print All the states of a particular or a set of countries.
            
        def geography_division_select(object, method, options = {}, html_options = {})
          InstanceTag.new(object, method, self, options.delete(:object)).to_geography_division_select_tag(options, html_options)
        end
        
        def geography_division_options_for_select(options={})
          type = options[:drilldown].nil? ? "region" : options[:drilldown].downcase
          onlyconditions  = options[:only]
          excludeconditions = options[:exclude]
          selected_options = ""
          selected=options[:selected]
          sel_region_options = Array.new
          prioritylist = options[:priority]
          case type
            when "region"
              #calculate constraints for region
              sel_region_options = get_regions(onlyconditions, excludeconditions)      
              if prioritylist
                selected_options+= options_for_select(prioritylist.split(","),selected)
                selected_options+="<option value='' disabled='disabled'>________________</option>"
              end
              selected_options+= options_for_select(sel_region_options.sort, selected)
            when "country"
              sel_country_options = get_countries(onlyconditions,excludeconditions)
              if prioritylist
                selected_options+= options_for_select(prioritylist.split(","),selected)
                selected_options+="<option value='' disabled='disabled'>________________</option>"
              end
              selected_options+= options_for_select(sel_country_options.sort, selected)
            when "state"
              sel_state_options = get_states(onlyconditions,excludeconditions)
              if prioritylist
                selected_options+= options_for_select(prioritylist.split(","),selected)
                selected_options+="<option value='' disabled='disabled'>________________</option>"
              end
              selected_options+= options_for_select(sel_state_options.sort, selected)
          end
          return selected_options
        end
       
       private 
        
        #Regions of the  World
        GEOGRAPHY_DIVISION_REGION = ["Africa", "Antartica","Asia", "Europe", "North America","Oceania","South America"] unless const_defined?("GEOGRAPHY_DIVISION_REGION")
        #Countries of the World based on Each Region
        GEOGRAPHY_DIVISION_AFRICA_COUNTRIES = ["Algeria","Angola","Benin","Botswana","Burkina Faso","Burundi","British Indian Ocean Territory","Cameroon","Cape Verde","Central African Republic","Chad","Comoros","Democratic Republic of Congo","Republic of Congo","Cote d'Ivoire","Djibouti","Egypt","Equatorial Guinea","Eritrea","Ethiopia","Gabon","Gambia","Ghana","Guinea","Guinea Bissau","Kenya","Lesotho","Liberia","Libya","Madagascar","Malawi","Mali","Mauritania","Mauritius","Mayotte","Morocco","Mozambique","Namibia","Niger","Nigeria","Reunion","Rwanda","St Helena","Sao Tome and Principe","Senegal","Seychelles","Sierra Leone","Somalia","South Africa","Sudan","Swaziland","Tanzania","Togo","Tunisia","Uganda","Western Sahara","Zambia","Zimbabwe"] unless const_defined?("GEOGRAPHY_DIVISION_AFRICA_COUNTRIES")
        GEOGRAPHY_DIVISION_ASIA_COUNTRIES = ["Afghanistan","Bahrain","Bangladesh","Bhutan","Brunei Darussalam","Cambodia","China","Hong Kong","India","Indonesia","Iran","Iraq","Israel","Japan","Jordan","Kazakhstan","North Korea","South Korea","Kuwait","Kyrgyzstan","Laos","Lebanon","Macau","Malaysia","Maldives","Mongolia","Myanmar","Nepal","Oman","Pakistan","Palestinian territories","Philippines","Qatar","Saudi Arabia","Singapore","Sri Lanka","Syria","Taiwan","Tajikistan","Thailand","Timor Leste","Turkmenistan","United Arab Emirates","Uzbekistan","Vietnam","Yemen"] unless const_defined?("GEOGRAPHY_DIVISION_ASIA_COUNTRIES")
        GEOGRAPHY_DIVISION_ANTARTICA_COUNTRIES = ["Bouvet Island","French Southern Territories","Heard and McDonald Islands","South Georgia and the South Sandwich Islands"]  unless const_defined?("GEOGRAPHY_DIVISION_ANTARTICA_COUNTRIES")
        GEOGRAPHY_DIVISION_OCEANIA_COUNTRIES = ["American Samoa","Australia","Cocos Islands","Cook Islands","Christmas Island","Fiji","French Polynesia","Guam","Kiribati","Marshall Islands","Micronesia","New Caledonia","New Zealand","Niue","Northern Mariana Islands","Palau","Papua New Guinea","Pitcairn Island","Samoa","Solomon Islands","Tokelau","Tonga","Tuvalu","Vanuatu","Wallis and Futuna Islands"]  unless const_defined?("GEOGRAPHY_DIVISION_OCEANIA_COUNTRIES")
        GEOGRAPHY_DIVISION_EUROPE_COUNTRIES = ["Albania","Andorra","Armenia","Austria","Azerbaijan","Belarus","Belgium","Bosnia and Herzegovina","Bulgaria","Czech Republic","Cyprus","Denmark","Estonia","Faeroe Islands","Finland","France","Germany","Georgia","Gibraltar","Greece","Guernsey","Hungary","Hrvatska","Iceland","Ireland","Isle of Man","Italy","Latvia","Liechtenstein","Lithuania","Luxembourg","Macedonia","Malta","Moldova","Monaco","Montenegro","Netherlands","Norway","Poland","Portugal","Romania","Russia","San Marino","Serbia","Slovakia","Slovenia","Spain","Sweden","Switzerland","Turkey","Ukraine","United Kingdom","Vatican city"]  unless const_defined?("GEOGRAPHY_DIVISION_EUROPE_COUNTRIES")
        GEOGRAPHY_DIVISION_NORTHAMERICA_COUNTRIES = ["Anguilla","Antigua and Barbuda","Aruba","Bahamas","Barbados","Belize","Bermuda","British Virgin Islands","Canada","Cayman Islands","Costa Rica","Cuba","Dominica","Dominican Republic","El Salvador","Greenland","Grenada","Guadaloupe","Guatemala","Haiti","Honduras","Jamaica","Martinique","Mexico","Montserrat","Netherlands Antilles","Nicaragua","Panama","Puerto Rico","St Barthelemy","St Kitts and Nevis","St Lucia","St Martin","St Pierre and Miquelon","St Vincent and the Grenadines","Trinidad and Tobago","Turks and Caicos Islands ","United States of America","United States Virgin Islands"]  unless const_defined?("GEOGRAPHY_DIVISION_NORTHAMERICA_COUNTRIES")
        GEOGRAPHY_DIVISION_SOUTHAMERICA_COUNTRIES = ["Argentina","Bolivia","Brazil","Chile","Colombia","Ecuador","Falkland Islands","French Guiana","Guyana","Paraguay","Peru","Suriname","Uruguay","Venezuela"]  unless const_defined?("GEOGRAPHY_DIVISION_SOUTHAMERICA_COUNTRIES")
        #Country Sub-Divisions Based on Each Country
        #A
        GEOGRAPHY_DIVISION_AFGHANISTAN_STATES=["Badakhshan","Badghis","Baghlan","Balkh","Bamyan","Daykundi","Farah","Faryab","Ghazni","Ghor","Helmand","Heart","Jowzjan","Kabul","Kandahar","Kapisa","Khost","Konar","Kunduz","Laghman","Lowgar","Nangarhar","Nimruz","Nurestan","Oruzgan","Paktia","Paktika","Panjshir","Parvan","Samangan","Sare Pol","Takhar","Wardak","Zabol"] unless const_defined?("GEOGRAPHY_DIVISION_AFGHANISTAN_STATES")
        GEOGRAPHY_DIVISION_ALBANIA_STATES=["Berat","Diver","Durres","Elbasan","Fier","Gjirokaster","Korce","Kukes","Lezhe","Shkoder","Tirana","Vlore"] unless const_defined?("GEOGRAPHY_DIVISION_ALBANIA_STATES")
        GEOGRAPHY_DIVISION_ALGERIA_STATES=["Adrar","Algiers","Ain Defla","Ain Temouchent","Annaba","Batna","Bechar","Bejaia","Biskra","Blida","Bouira","Bordj Bou Arreridj","Boumerdes","Chlef","Constantine","Djelfa","El Tarf","El Bayadh","El Oued","Ghardaia","Guelma","Illizi","Jijel","Khenchela","Laghouat","Medea","Mostaganem","M'Sila","Mascara","Mila","Naama","Oum el-Bouaghi","Ouargla","Oran","Relizane","Setif","Saida","Skikda","Sidi Bel Abbes","Souk Ahras","Tamanghasset","Tebessa","Tlemcen","Tiaret","Tizi Ouzou","Tindouf","Tissemsilt","Tipasa"] unless const_defined?("GEOGRAPHY_DIVISION_ALGERIA_STATES")
        GEOGRAPHY_DIVISION_AMERICANSAMOA_STATES=["Faleasao","Fitiuta","Ituau","Lealataua","Leasina","Ma'Oputasi","Ofu","Olosega","Sa'Ole","Sua","Ta'u","Tualatai","Tualauta","Vaifanua"] unless const_defined?("GEOGRAPHY_DIVISION_AMERICANSAMOA_STATES")
        GEOGRAPHY_DIVISION_ANDORRA_STATES=["Andorra la Vella","Canillo","Encamp","Escaldes-Engordany","La Massana","Ordino","Sant Julia de Loria"] unless const_defined?("GEOGRAPHY_DIVISION_ANDORRA_STATES")
        GEOGRAPHY_DIVISION_ANGOLA_STATES=["Bengo","Benguela","Bie","Cabinda","Cuando Cubango","Cuanza Norte","Cuanza Sul","Cunene","Huambo","Huila","Luanda","Lunda Norte","Lunda Sul","Malanje","Moxico","Namibe","Uige","Zaire"] unless const_defined?("GEOGRAPHY_DIVISION_ANGOLA_STATES")
        GEOGRAPHY_DIVISION_ANGUILLA_STATES=["Anguillita","Dog Island","Prickly Pear Cays","Scrub Island","Seal Island","Sombrero","Sandy Island"] unless const_defined?("GEOGRAPHY_DIVISION_ANGUILLA_STATES")
        GEOGRAPHY_DIVISION_ANTIGUAANDBARBUDA_STATES=["Antigua","Barbuda"] unless const_defined?("GEOGRAPHY_DIVISION_ANTIGUAANDBARBUDA_STATES")
        GEOGRAPHY_DIVISION_ARGENTINA_STATES=["Provincia de Buenos Aires","Catamarca","Chaco","Chubut","Cordoba","Corrientes","Entre Rios","Formosa","Jujuy","La Pampa","La Rioja","Mendoza","Misiones","Neuquen","Rio Negro","Salta","San Luis","San Juan","Santa Cruz","Santa Fe","Santiago del Estero","Tierra del Fuego","Tucuman"] unless const_defined?("GEOGRAPHY_DIVISION_ARGENTINA_STATES")
        GEOGRAPHY_DIVISION_ARMENIA_STATES=["Aragatsotn","Ararat","Armavir","Gegharkunik","Kotayk","Lori","Shirak","Syunik","Tavush","Vayots Dzor","Yerevan"] unless const_defined?("GEOGRAPHY_DIVISION_ARMENIA_STATES")
        GEOGRAPHY_DIVISION_ARUBA_STATES=[] unless const_defined?("GEOGRAPHY_DIVISION_ARUBA_STATES")
        GEOGRAPHY_DIVISION_AUSTRALIA_STATES=["Ashmore and Cartier Islands","Australian Antarctic Territory","Australian Capital Territory","Christmas Island","Cocos Islands","Coral Sea IslandsTerritory","Hearld Island and McDonald Islands","Jervis Bay Territory+","New South Wales","Norfolk Island","Northen Territory","Queensland","South Australia","Tasmania","Victoria","Western Australia"] unless const_defined?("GEOGRAPHY_DIVISION_AUSTRALIA_STATES")
        GEOGRAPHY_DIVISION_AUSTRIA_STATES=["Burgenland","Carinthia","Lower Austria","Upper Austria","Salzburg","Styria","Tyrol","Vorarlberg","Vienna"] unless const_defined?("GEOGRAPHY_DIVISION_AUSTRIA_STATES")
        GEOGRAPHY_DIVISION_AZERBAIJAN_STATES=["Absheron","Aghjabadi","Agdam","Agdash","Agstafa","Agsu","Shirvan city","Astara","Baku city","Balakan","Barda","Beylagan","Bilasuvar","Jabrayil","Jalilabad","Dashkasan","Davachi","Fizuli","Gadabay","Ganja city","Goranboy","Goychay","Hajigabul","Imishli","Ismailli","Kalbajar","Kurdamir","Lachin","Lankaran","Lankaran city","Lerik","Masally","Mingachevir city","Naftalan city","Neftchala","Oghuz","Qabala","Qazakh","Gobustan","Quba","Qubadli","Qusar","Saatly","Sabirabad","Shaki","Shaki city","Salyan","Shamakhi","Shamkir","Samukh","Siazan","Sumqayit city","Shusha","Shusha city","Tartar","Tovuz","Ujar","Khachmaz","Khankendi city","Goygol","Khizi","Khojali","Khojavend","Yardymli","Yevlakh","Yevlakh city","Zangilan","Zaqatala","Zardab"] unless const_defined?("GEOGRAPHY_DIVISION_AZERBAIJAN_STATES")
        #B
        GEOGRAPHY_DIVISION_BAHAMAS_STATES=["Acklins","Berry Islands","Bimini","Black Point","Exuma","Cat Island","Central Abaco","Central Andros","Central Eleuthera","Grand Bahama","Crooked Island","East Grand Bahama","Exuma","Grand cay","Abaco","Inagua","Long Island","Mangrove cay(Andros)","Mayaguana","Moore's Island(Abaco)","North Abaco","North Andros","North Eleuthera","Ragged Island","Rum Cay","San Salvador","South Aboaco","South Andros","South Eleuthera","West Grand Bahama"] unless const_defined?("GEOGRAPHY_DIVISION_BAHAMAS_STATES")
        GEOGRAPHY_DIVISION_BAHRAIN_STATES=["Capital Governorate","Central governorate","Muharraq Governorate","Northern Governorate","Southern Governorate"] unless const_defined?("GEOGRAPHY_DIVISION_BAHRAIN_STATES")
        GEOGRAPHY_DIVISION_BANGLADESH_STATES=["Barisal","Chittagong","Dhaka","Khulna","Rajshahi","Sylhet"] unless const_defined?("GEOGRAPHY_DIVISION_BANGLADESH_STATES")
        GEOGRAPHY_DIVISION_BARBADOS_STATES=["Christ church","Saint Andrew","Saint George","Saint James","Saint John","Saint Joseph","Saint Lucy","Saint Michael","Saint Peter","Saint Philip","Saint Thomas"] unless const_defined?("GEOGRAPHY_DIVISION_BARBADOS_STATES")
        GEOGRAPHY_DIVISION_BELARUS_STATES=["Brest Voblast","Gomel Voblast","Grodno Voblast","Mogilev Voblast","Minsk Voblast","Vitebsk Voblast"] unless const_defined?("GEOGRAPHY_DIVISION_BELARUS_STATES")
        GEOGRAPHY_DIVISION_BELGIUM_STATES=["Flemish Region","Wallon Region","Brussels-capital Region"] unless const_defined?("GEOGRAPHY_DIVISION_BELGIUM_STATES")
        GEOGRAPHY_DIVISION_BELIZE_STATES=["Belize","Cayo","Corozal","Orange Walk","Stann Creek","Toledo"] unless const_defined?("GEOGRAPHY_DIVISION_BELIZE_STATES")
        GEOGRAPHY_DIVISION_BENIN_STATES=["Alibori","Atakora","Atlantique","Borgou","Collines","Donga","Kouffo","Littoral","Mono","Oueme","Plateau","Zou"] unless const_defined?("GEOGRAPHY_DIVISION_BENIN_STATES")
        GEOGRAPHY_DIVISION_BERMUDA_STATES=["Devonshire","Hamilton","Paget","Pembroke","St George's","Sandys","Smith's","Southampton","Warwick"] unless const_defined?("GEOGRAPHY_DIVISION_BERMUDA_STATES")
        GEOGRAPHY_DIVISION_BHUTAN_STATES=["Bumthang","Chukha","Dagana","Gasa","Haa","Lhuntse","Mongar","Paro","Pemagatshel","Punakha","Samdrup Jongkhar","Samtse","Sarpang","Thimphu","Trashigang","Trashiyangtse","Trongsa","Tsirang","Wangdue Phodrang","Zhemgang"] unless const_defined?("GEOGRAPHY_DIVISION_BHUTAN_STATES")
        GEOGRAPHY_DIVISION_BOLIVIA_STATES=["Beni","Chuquisaca","Cochabamba","La Paz","Oruro","Pando","Potosi","Sants Cruz","Tarija"] unless const_defined?("GEOGRAPHY_DIVISION_BOLIVIA_STATES")
        GEOGRAPHY_DIVISION_BOSNIAANDHERZEGOVINA_STATES=["Federacija Bosne i Hercegovine","Republika Srpska","Brcko District"] unless const_defined?("GEOGRAPHY_DIVISION_BOSNIAANDHERZEGOVINA_STATES")
        GEOGRAPHY_DIVISION_BOTSWANA_STATES=["Central","Ghanzi","Kgalagadi","Kgatleng","Kweneng","North-East","North-West","South-East","Southern"] unless const_defined?("GEOGRAPHY_DIVISION_BOTSWANA_STATES")
        GEOGRAPHY_DIVISION_BOUVETISLAND_STATES=[] unless const_defined?("GEOGRAPHY_DIVISION_BOUVETISLAND_STATES")
        GEOGRAPHY_DIVISION_BRAZIL_STATES=["Acre","Alagoas","Amapa","Amazonas","Bahia","Ceara","Distrito Federal","Espirito Santo","Goias","Maranhao","Mato Grosso","Mato Grosso do Sul","Minas Gerais","Para","Paraiba","Parana","Pernambuco","Piaui","Rio die Janeiro","Rio Grande do Norte","Rio Grande do Sul","Rondonia","Roraima","Santa Catarina","Sao Paulo","Sergipe","Tocantins"] unless const_defined?("GEOGRAPHY_DIVISION_BRAZIL_STATES")
        GEOGRAPHY_DIVISION_BRITISHINDIANOCEANTERRITORY_STATES=[] unless const_defined?("GEOGRAPHY_DIVISION_BRITISHINDIANOCEANTERRITORY_STATES")
        GEOGRAPHY_DIVISION_BRITISHVIRGINISLANDS_STATES=["Anegada","Beef","Cooper","Ginger","Great Camanoe","Great Thatch","Guana Mosquito","Jost Van Dyke","Necker","Norman","Peter","Salt","Tortola","Virgin Gorda"] unless const_defined?("GEOGRAPHY_DIVISION_BRITISHVIRGINISLANDS_STATES")
        GEOGRAPHY_DIVISION_BRUNEIDARUSSALAM_STATES=["Belait","Brunei and Muara","Temburong","Tutong"]   unless const_defined?("GEOGRAPHY_DIVISION_BRUNEIDARUSSALAM_STATES")
        GEOGRAPHY_DIVISION_BULGARIA_STATES=["Blagoevgrad","Burgas","Dobrich","Gabrovo","Haskovo","Kardzhali","Kyustendil","Lovench","Montana","Paxardzhik","Pernik","Pleven","Plovdiv","Razgrad","Ruse","Shumen","Silistra","Sliven","Smolyan","Sofia","Stara Zagora","Targovishte","Varna","Veliko","Tarnovo","Vidin","Vratsa","Yambol"] unless const_defined?("GEOGRAPHY_DIVISION_BULGARIA_STATES")
        GEOGRAPHY_DIVISION_BURKINAFASO_STATES=["Bale","Bam","Banwa","Bazega","Bougouriba","Boulgou","Boulkiemde","Comoe","Ganzourgou Gnagna","Gourma","Houet","Ioba","Kadiogo","Kenedougou","Komondjari","Kompienga","Kossi","Koulpelogo","Kouritenga","Kourweogo","Leraba","Loroum Mouhoun","Nahouri","Namentenga","Nayala","Noumbiel","Oubritenga","Oudalan","Passore","Poni Sanguie","Sanmatenga","Seno","SissiliSoum","Sourou","Tapoa","Tuy","Yagha","Yatenga","Ziro","Zondoma","Zoundweogo"] unless const_defined?("GEOGRAPHY_DIVISION_BURKINAFASO_STATES")
        GEOGRAPHY_DIVISION_BURUNDI_STATES=["Bubanza","Bujumbura Mairie","Bujumbura Rural","Bururi","Cankuzo","Cibitoke","Gitega","Karuzi","Kayanza","Kirundo","Makamba","Muramvya","Muyinga","Mwaro","Ngozi","Rutana","Ruyigi"] unless const_defined?("GEOGRAPHY_DIVISION_BURUNDI_STATES")
        #C
        GEOGRAPHY_DIVISION_CAMBODIA_STATES=["Banteay Meanchey","Battambang","Kampong Cham","Kampong Chhnang","Kampong Speu","Kampong Thom","Kampot","Kandal","Koh Kong","Kep","Kratie","Mondulkiri","Oddar Meancheay","Pailin","Phnom Penh","Sihanoukville","Preah Vihear","Pursat","Prey Veng","Ratanakiri","Siem Reap","Stung Treng","Svay Rieng","Takeo"] unless const_defined?("GEOGRAPHY_DIVISION_CAMBODIA_STATES")
        GEOGRAPHY_DIVISION_CAMEROON_STATES=["Adamawa","Centre","East","Far North","Littoral","North","Northwest","South","Southwest","West"] unless const_defined?("GEOGRAPHY_DIVISION_CAMEROON_STATES")
        GEOGRAPHY_DIVISION_CANADA_STATES=["Alberta","British Columbia","Manitoba","New Brunswick","Newfoundland and Labrador","Nova Scotia","Ontario","Prince Edward Island","Quebec","Saskatchewan","Northwest Territories","Nunavut","Yukon"] unless const_defined?("GEOGRAPHY_DIVISION_CANADA_STATES")
        GEOGRAPHY_DIVISION_CAPEVERDE_STATES=["Brava","Boa Vista","Fogo","Maio","Santiago","Sal","Santa Luzia","Santo Antao","Sao Nicolau","SaoVicente"] unless const_defined?("GEOGRAPHY_DIVISION_CAPEVERDE_STATES")
        GEOGRAPHY_DIVISION_CAYMANISLANDS_STATES=[] unless const_defined?("GEOGRAPHY_DIVISION_CAYMANISLANDS_STATES")
        GEOGRAPHY_DIVISION_CENTRALAFRICANREPUBLIC_STATES=["Bamingui-Bangoran","Basse-Kotto","Haute-Kotto","Haut-Mbomou","Kemo","Lobaye","Mambere-Kadei","Mbomou","Nana-Mambere","Ombella-M'Poko","Ouaka","Ouham","Ouham-Pende","Vakaga"] unless const_defined?("GEOGRAPHY_DIVISION_CENTRALAFRICANREPUBLIC_STATES")
        GEOGRAPHY_DIVISION_CHAD_STATES=["Batha","Borkou-Ennedi-Tibesti","Chari-Baguirmi","Guera","Hadjer-Lamis","Kanem","Lac","Logone Occidental","Logone Oriental","Mandoul","Mayo-kebbi Est","Mayo-kebbi Ouest","Moyen-Chari","Ouaddai","Salamat","Tandjile","Wadi Fira","N'Djamena"]   unless const_defined?("GEOGRAPHY_DIVISION_CHAD_STATES")
        GEOGRAPHY_DIVISION_CHILE_STATES=["Arica and Parinacota","Antofagasta","Atacama","Araucania","Aisen","Biobio","Coquimbo","Los Rios","Los Lagos","Magallanes and Antartica Chilena","Maule","O'Higgins","Santiago Metropolitan","Tarapaca","Valparaiso"] unless const_defined?("GEOGRAPHY_DIVISION_CHILE_STATES")
        GEOGRAPHY_DIVISION_CHINA_STATES=["Anhui","Fujian","Gansu","Guizhou","Guangdong","Heilongjiang","Hebei","Hubei","Henan","Hunan","Hainan","Jilin","Jiangsu","Jiangxi","Liaoning","Qinghai","Shaanxi","Shanxi","Sichuan","Shandong","Yunnan","Zhejiang"] unless const_defined?("GEOGRAPHY_DIVISION_CHINA_STATES")
        GEOGRAPHY_DIVISION_CHRISTMASISLAND_STATES=[] unless const_defined?("GEOGRAPHY_DIVISION_CHRISTMASISLAND_STATES")
        GEOGRAPHY_DIVISION_COCOSISLANDS_STATES=["Horsburgh Island","Direction Island","Workhouse Island","Prison Island","Button Islets","Woeplace Islets","Home Island","Scaevola Islet","Canui Island","Ampang Minor","Goldwater Island","Thorn Island","Gooseberry Island","Misery Island","Goat Island","Middle Mission Island","South Goat Island","South Island","North Goat Island","East Cay","Burial Island","West Cay","Keelingham Horn Island","West Island","Turtle Island"] unless const_defined?("GEOGRAPHY_DIVISION_COCOSISLANDS_STATES")
        GEOGRAPHY_DIVISION_COLOMBIA_STATES=["Amazonas","Antioquia","Arauca","Atlantico","Bolivar","Boyaca","Caldas","Caqueta","Casanare","Cauca","Cesar","Choco","Cordoba","Cundinamarca","Guainia","Guaviare","Huila","La Guajira","Magdalena","Meta","Narino North Santander","Putumayo","Quindio","Risaralda","San Andres","Providencia and Santa Catalina","Santander","Sucre","Tolima","Valle del Cauca","Vaupes","Vichada","Capital District"] unless const_defined?("GEOGRAPHY_DIVISION_COLOMBIA_STATES")
        GEOGRAPHY_DIVISION_COMOROS_STATES=["Ngazidja","Mwali","Nzwani","Mahore"] unless const_defined?("GEOGRAPHY_DIVISION_COMOROS_STATES")
        GEOGRAPHY_DIVISION_DEMOCRATICREPUBLICOFCONGO_STATES=["Bas-Uele","Equateur","Haut-Lomami","Haut-Katanga","Haut-Uele","Ituri","Kasai Oriental","Kinshasa","Kongo Central","Kwango","Kwilu","Kasai","Kasai Oriental","Lulua","Lomami","Lualaba","Mai-Ndombe","Maniema","Mongala","Nord-Kivu","Nord-Ubangi","Sankuru","Sud-Kivu","Sud-Ubangi","Tshopo","Tshuapa","Tanganyika"]   unless const_defined?("GEOGRAPHY_DIVISION_DEMOCRATICREPUBLICOFCONGO_STATES")
        GEOGRAPHY_DIVISION_REPUBLICOFCONGO_STATES=["Bouenza","Cuvette","Cuvette-Ouest","Kouilou","Lekoumou","Commune of Brazzaville","Likouala","Niari","Plateaux","Pool","Sangha"]   unless const_defined?("GEOGRAPHY_DIVISION_REPUBLICOFCONGO_STATES")
        GEOGRAPHY_DIVISION_COOKISLANDS_STATES=["Aitutaki","Atiu","Mangaia","Mauke","Mitiaro","Manuae","Manihiki","Nassau","Penrhyn","Pukapuka","Palmerston","Rakahanga","Rarotonga","Suwarrow","Tema Reef","Takutea","Winslow Reef"] unless const_defined?("GEOGRAPHY_DIVISION_COOKISLANDS_STATES")
        GEOGRAPHY_DIVISION_COSTARICA_STATES=["Alajuela","Cartago","Guanacaste","Heredia","Limon","Puntarena","San Jose"] unless const_defined?("GEOGRAPHY_DIVISION_COSTARICA_STATES")
        GEOGRAPHY_DIVISION_COTEDIVOIRE_STATES=["Agneby","Bafing","Bas-Sassandra","Denguele","Dix-Huit Montagnes","Fromager","Haut-Sassandra","Lacs","Lagunes","Marahoue","Moyen-Cavally","Moyen-Comoe","N'zi-Comoe","Savanes","Sud-Bandama","Sud-Comoe","Vallee du Bandama","Worodougou","Zanzan"] unless const_defined?("GEOGRAPHY_DIVISION_COTEDIVOIRE_STATES")
        GEOGRAPHY_DIVISION_CUBA_STATES=["Ciudad de La Habana","Cienfuegos","Camaguey","Ciego de Avila","Granma","Guantanamo","Holguin","La Habana","Las Tunas","Matanzas","Pinar del Rio","Sancti Spiritus","Santiago de Cuba","Villa Clara"] unless const_defined?("GEOGRAPHY_DIVISION_CUBA_STATES")
        GEOGRAPHY_DIVISION_CYPRUS_STATES=["Famagusta","Kyrenia","Larnaca","Limassol","Nicosia","Paphos"] unless const_defined?("GEOGRAPHY_DIVISION_CYPRUS_STATES")
        GEOGRAPHY_DIVISION_CZECHREPUBLIC_STATES=["Central Bohemian","Hradec Kralove","Karlovy Vary","Liberec","Moravian-Silesian","Olomouc","Plzen","Pardubice","South Bohemian","South Moravian","Usti nad Labem","Vsocina","Zlin"] unless const_defined?("GEOGRAPHY_DIVISION_CZECHREPUBLIC_STATES")
        #D
        GEOGRAPHY_DIVISION_DENMARK_STATES=["Hovendstaden","Midtjylland","Nordjylland","Sjaelland","Syddanmark"] unless const_defined?("GEOGRAPHY_DIVISION_DENMARK_STATES")
        GEOGRAPHY_DIVISION_DJIBOUTI_STATES=["Alaili Dadda","Ali Sabieh","As Eyla","Balha","Dikhil","Djibouti","Dorra","Obock","Randa","Tadjourah","Yoboki"] unless const_defined?("GEOGRAPHY_DIVISION_DJIBOUTI_STATES")
        GEOGRAPHY_DIVISION_DOMINICA_STATES=["Saint Andrew","Saint David","Saint George","Saint John","Saint Joseph","Saint Luke","Saint Mark","Saint Patrick","Saint Paul","Saint Peter"] unless const_defined?("GEOGRAPHY_DIVISION_DOMINICA_STATES")
        GEOGRAPHY_DIVISION_DOMINICANREPUBLIC_STATES=["Azua","Baoruco","Barahona","Dajabon","Distrito Nacional","Duarte","Elias Pina El Seibo","Espaillat","Hato Mayor","Hermanas Mirabal","Independencia","La Altagracia","La Romanam","La Vega","Maria Trinidad Sanchez","Monsenor Nouel","Monte Cristi","Monte Plata","Pedernales Peravia","Puerto Plata","Samana","Sanchez Ramirez","San Cristobal","San Jose de Ocoa","San Juan","San Pedro de Macoris","Santiago","Santiago Rodriguez","Santo Domingo","Valverde"] unless const_defined?("GEOGRAPHY_DIVISION_DOMINICANREPUBLIC_STATES")
        #E
        GEOGRAPHY_DIVISION_ECUADOR_STATES=["Azuay","Bolivar","Canar","Carchi","Chimborazo","Cotopaxi","El Oro","Esmeraldas","Galapagos","Guayas","Imbabura","Loja","Los Rios","Manabi","Morona-Santiago","Napo","Orellana","Pastaza","Pichincha","Santa Elena","Santo Domingo de los Tsachilas","Sucumbios","Tungurahua","Zamora-Chinchipe"] unless const_defined?("GEOGRAPHY_DIVISION_ECUADOR_STATES")
        GEOGRAPHY_DIVISION_EGYPT_STATES=["Alexandria","Aswan","Asyut","Beheira","Beni Suef","Cairo","Dakahlia","Damietta","Faiyum","Gharbia","Giza","Helwan","Ismailia","Kafr el-Sheikh","Luxor","Matruh","Minya","Monufia","New Valley","North Sinai","Port Said","Qalyubia","Qena","Red Sea","Sharqia","Sohag","South Sinai","Suez"]   unless const_defined?("GEOGRAPHY_DIVISION_EGYPT_STATES")
        GEOGRAPHY_DIVISION_ELSALVADOR_STATES=["Ahuachapan","Cabarias","Chalatenango","Cuscatlan","La Libertad","La Paz","La Union","Morazan","San Miguel","San Slavador","San Vicente","Santa Ana","Sonsonate","Usulutan"]  unless const_defined?("GEOGRAPHY_DIVISION_ELSALVADOR_STATES")
        GEOGRAPHY_DIVISION_EQUATORIALGUINEA_STATES=["Annogon","Bioko Norte","Bioko Sur","Centro Sur","Kie-Ntem","Litoral","Wele-Nzas"] unless const_defined?("GEOGRAPHY_DIVISION_EQUATORIALGUINEA_STATES")
        GEOGRAPHY_DIVISION_ERITREA_STATES=["Anseba","Central","Gash-Barka","Northern Red Sea","Southern","Southern Red Sea"] unless const_defined?("GEOGRAPHY_DIVISION_ERITREA_STATES")
        GEOGRAPHY_DIVISION_ESTONIA_STATES=["Harjumaa","Hiiumaa","Ida-Virumaa","Jarvamaa","Jogevamaa","Laanemaa","Laane-Virumaa","Parnumaa","Polvamaa","Raplamaa","Saaremaa","Tartumaa","Valgamaa","Viljandimaa","Vorumaa Petserimaa"] unless const_defined?("GEOGRAPHY_DIVISION_ESTONIA_STATES")
        GEOGRAPHY_DIVISION_ETHIOPIA_STATES=["Addis","Ababa","Afar","Amahara","Benishangul-Gumu","Dire","Dawa","Gambela","Harari","Nationalities and People's Region","Oromia","Somali","Southern Nations","Tigray"] unless const_defined?("GEOGRAPHY_DIVISION_ETHIOPIA_STATES")
        #F
        GEOGRAPHY_DIVISION_FAEROEISLANDS_STATES=["Klaksvik","Northern Eysturoy","Norooyggjar","Streymoy","Suouroy","Vagar"] unless const_defined?("GEOGRAPHY_DIVISION_FAEROEISLANDS_STATES")
        GEOGRAPHY_DIVISION_FALKLANDISLANDS_STATES=["Barren Island (Falkland Islands)","Beauchene Island","Beaver Island (Falkland Islands)","Bleaker Island","Carcass Island","East Falkland","George Island","Golding Island","Grand Jason Island","Jason Islands","Keppel Island","Lafonia (peninsula)","Lively Island","New Island","Passage Islands","Pebble Island","Saunders Island (Falkland Islands)","Sea Lion Island","Speedwell Island","Staats Island","Steeple Jason Island","Swan Islands","Weddell Island","West Falkland","West Point Island"] unless const_defined?("GEOGRAPHY_DIVISION_FALKLANDISLANDS_STATES")
        GEOGRAPHY_DIVISION_FIJI_STATES=["Bua","Ba","Cakaudrove","Kadavu","Lau","Lomaiviti","Macuata","Naitasiri","Namosi","Nadroga-Navosa","Rewa","Ra","Serua","Tailevu"] unless const_defined?("GEOGRAPHY_DIVISION_FIJI_STATES")
        GEOGRAPHY_DIVISION_FINLAND_STATES=["Aland","Eastern Finland","Oulu","Lapland","Southern Finland","Western Finland"] unless const_defined?("GEOGRAPHY_DIVISION_FINLAND_STATES")
        GEOGRAPHY_DIVISION_FRANCE_STATES=["Alsace","Aquitaine","Auvergne","Basse-Normandie","Bourgogne","Bretagne","Centre","Champagne-Ardenne","Corse","Franche-Comte","Haute-Normandie","Ile-de-France","Languedoc-Roussillon","Limousin","Loraine","Midi-Pyrenees","Pays-de-la-Loire","Picardie","Poitou-Charentes","Provence-Alpes-Cote D'Azur","Rhone-Alpes"] unless const_defined?("GEOGRAPHY_DIVISION_FRANCE_STATES")
        GEOGRAPHY_DIVISION_FRENCHGUIANA_STATES=["AwalaYalimapo","Apatou","GrandSanti","Camopi","Cayenne","Iracoubo","Kourou","Mana","Maripasoula","Macouria","Montsinery-Tonegrande","Matoury","Ouanary","Papaichton","Regina","Roura","Remire-Montjoly","Saul","Saint-Laurent-du-Maroni","Saint-Elie","Sinnamary","Saint-George"] unless const_defined?("GEOGRAPHY_DIVISION_FRENCHGUIANA_STATES")
        GEOGRAPHY_DIVISION_FRENCHPOLYNESIA_STATES=["Austral Island","Leeward Island","Marquesas Island","Tuamotu-Gambier","Windward Island"] unless const_defined?("GEOGRAPHY_DIVISION_FRENCHPOLYNESIA_STATES")
        GEOGRAPHY_DIVISION_FRENCHSOUTHERNTERRITORIES_STATES=["Archipel Crozet","Archipel des kerguelen","Iles Saint Paul Et Amsterdam","Iles Eparses","Terre Adelie"] unless const_defined?("GEOGRAPHY_DIVISION_FRENCHSOUTHERNTERRITORIES_STATES")
        #G
        GEOGRAPHY_DIVISION_GABON_STATES=["Estuaire","Haut-Ogooue","Moyen-Ogooue","Ngounie","Nyanga","Ogooue-Ivindo","Ogooue-Lolo","Ogooue-Maritime","Woleu-Ntem"] unless const_defined?("GEOGRAPHY_DIVISION_GABON_STATES")
        GEOGRAPHY_DIVISION_GAMBIA_STATES=["Banjul","Central Baddibu","Fulladu West","Fulladu East","Janjanbureh","Jarra Central","Jarra East","Jokadu","Jarra West","Kiang Central","Kiang East","Kiang West","Kantora","Kanifing","Lower saloum","Lower Baddibu","Lower Niumi","Niamina Dankunku","Niamina East","Niamina West","Niani","Nianija","Sami","Sandu","Upper Saloum","Upper Baddibu","Upper Niumi","Wuli"] unless const_defined?("GEOGRAPHY_DIVISION_GAMBIA_STATES")
        GEOGRAPHY_DIVISION_GEORGIA_STATES=["Abkhazia","Adjara","Guria","Imereti","Kvemo Kartli","Kakheti","Mtskheta-Mtianeti","Racha-Lechkhumi","Kvemo Svaneti","Samtskhe-Javakheti","Shida Kartl","Samegrelo-Zemo Svaneti","Tbilisi"] unless const_defined?("GEOGRAPHY_DIVISION_GEORGIA_STATES")
        GEOGRAPHY_DIVISION_GERMANY_STATES=["Baden-Wurttemberg","Bavaria","Berlin","Brandenburg","Bremen","Hamburg","Hesse","Lower Saxony","Mecklenburg-Vorpommern","North Rhine-Westphalia","Rhineland-Palatinate","Saarland","Saxony","Saxony-Anhalt","Schleswig-Holstein","Thuringia"] unless const_defined?("GEOGRAPHY_DIVISION_GERMANY_STATES")
        GEOGRAPHY_DIVISION_GHANA_STATES=["Ashanti","Brong Ahafo","Central","Eastern","Greater Accra","Northern","Upper East","Upper West","Volta","Western"] unless const_defined?("GEOGRAPHY_DIVISION_GHANA_STATES")
        GEOGRAPHY_DIVISION_GIBRALTAR_STATES=["East Side","North District","Reclamation","Sandpits","South District","Town","Upper Town"] unless const_defined?("GEOGRAPHY_DIVISION_GIBRALTAR_STATES")
        GEOGRAPHY_DIVISION_GREECE_STATES=["Attica","Central Greece","Central Macedonia","Crete","East Macedonia and Thrace","Epirus","Ionian Islands","North Aegean","Peloponnese","South Aegean","Thessaly","West Greece","West Macedonia"] unless const_defined?("GEOGRAPHY_DIVISION_GREECE_STATES")
        GEOGRAPHY_DIVISION_GREENLAND_STATES=["Avanna (North Greenland)","Kitaa (West Greenland)","Tunu (East Greenland)"] unless const_defined?("GEOGRAPHY_DIVISION_GREENLAND_STATES")
        GEOGRAPHY_DIVISION_GRENADA_STATES=["Saint Andrew","Saint David","Saint Geroge","Saint John","Saint Mark","Saint Patrick"] unless const_defined?("GEOGRAPHY_DIVISION_GRENADA_STATES")
        GEOGRAPHY_DIVISION_GUERNSEY_STATES=["Castel","Forest","St.Andrew","St.Martin","St.Peter Port","St.Pierre du Bois","St.Sampson","St.Saviour","Torteval","Vale"] unless const_defined?("GEOGRAPHY_DIVISION_GUERNSEY_STATES")
        GEOGRAPHY_DIVISION_GUADALOUPE_STATES=["Anse-Bertrand","Baie-Mahault","Basse-Terre 1st Canton","Basse-Terre 2nd Canton","Bouillante","Capesterre-Belle-Eau 1st Canton","Capesterre-de-Marie-Galante","Capesterre-Belle-Eau 2nd Canton","Grand-Bourg,Gourbeyre","Goyave","Les Abymes 1st Canton","Les Abymes 2nd Canton","Les Abymes 3rd Canton","Les Abymes 4th Canton","Les Abymes 5th Canton","La Desirade","Le Gosier 1st Canton","Le Gosier 2nd Canton Le Moule 1st Canton","Le Moule 2nd Canton","Les Saintes","Lamentin","Morne-a-l'Eau 1st Canton","Morne-a-l'Eau 2nd Canton","Petit-Bourg","Petit-Canal","Pointe-a-Pitre 1st Canton","Pointe-a-Pitre 2nd Canton","Pointe-a-Pitre 3rd Canton","Pointe-Noire","Sainte-Anne 1st Canton","Sainte-Anne 2nd Canton","Saint-Francois","Saint-Louis","Saint-Claude","Sainte-Rose 1st Canton","Sainte-Rose 2nd Canton","Trois-Rivieres","Vieux-Habitants"] unless const_defined?("GEOGRAPHY_DIVISION_GUADALOUPE_STATES")
        GEOGRAPHY_DIVISION_GUAM_STATES=["Agana Heights","Agat","Asan Maina","Barrigada","Chalan Pago Ordot","Dededo","Hagatna","Inarajan","Mangilao","Merizo","Mongmong Toto Maite","Piti","Santa Rita","Sinajana","Talofofo","Tamuning","Umatac","Yigo","Yona"] unless const_defined?("GEOGRAPHY_DIVISION_GUAM_STATES")
        GEOGRAPHY_DIVISION_GUATEMALA_STATES=["Alta Verapaz","Baja Verapaz","Chimaltenango","Chiquimula","Peten","El Progreso","El Quiche","Escuintla","Guatemala","Huehuetenango","Izabal","Jalapa","Jutiapa","Quetzaltenango","Retalhuleu","Sacatepequez","San Marcos","Santa Rosa","Solola","Suchitepequez","Totonicapan","Zacapa"] unless const_defined?("GEOGRAPHY_DIVISION_GUATEMALA_STATES")
        GEOGRAPHY_DIVISION_GUINEA_STATES=["Boke Region","Conakry Region","Faranah Region","Kankan Region","Kindia Region","Labe Region","Mamou Region","Nzerekore Region"] unless const_defined?("GEOGRAPHY_DIVISION_GUINEA_STATES")
        GEOGRAPHY_DIVISION_GUINEABISSAU_STATES=["Bafata","Biombo","Bissau","Bolama","Cacheu","Gabu","Oio","Quinara","Tombali"] unless const_defined?("GEOGRAPHY_DIVISION_GUINEABISSAU_STATES")
        GEOGRAPHY_DIVISION_GUYANA_STATES=["Barima-Waini","Cuyuni-Mazaruni","Demerara-Mahaica","Essequibo Islands-West Demerara","East Berbice Corentyne","Mahaica-Berbice","Pomeroon-Supenaam","Potaro-Siparuni","Upper Takutu-Upper Essequibo","Upper Demerara-Berbice"] unless const_defined?("GEOGRAPHY_DIVISION_GUYANA_STATES")
        #H
        GEOGRAPHY_DIVISION_HAITI_STATES=["Artibonite","Centre","Grand'Anse","Nippes","Nord","Nord-Est","Nord-Ouest","Ouest","Sud-Est","Sud"] unless const_defined?("GEOGRAPHY_DIVISION_HAITI_STATES")
        GEOGRAPHY_DIVISION_HEARDANDMCDONALDISLANDS_STATES=["Heard Island","McDonald Island"] unless const_defined?("GEOGRAPHY_DIVISION_HEARDANDMCDONALDISLANDS_STATES")
        GEOGRAPHY_DIVISION_HOLYSEE_STATES=[] unless const_defined?("GEOGRAPHY_DIVISION_HOLYSEE_STATES")
        GEOGRAPHY_DIVISION_HONDURAS_STATES=["Atlantida","Choluteca","Colon","Comayagua","Copan","Cortes","El Paraiso","Francisco Morazan","Gracias a Dios","Intibuca","Islas de la Bahia","La Paz","Lempira","Ocotepeque","Olancho","Santa Barbara","Valle","Yoro"] unless const_defined?("GEOGRAPHY_DIVISION_HONDURAS_STATES")
        GEOGRAPHY_DIVISION_HONGKONG_STATES=["Central and Western","Eastern","Hong Kong Island","Kowloon Islands","Kowloon City","Kwun Tong","Kwai Tsing","New Territories","North","Sha Tin","Sai Kung","Sham Shui Po","Southern","Tai Po","Tsuen Wan","Tuen Mun","Wong Tai Sin","Wan Chai","Yuen Long","Yau Tsim Mong"] unless const_defined?("GEOGRAPHY_DIVISION_HONGKONG_STATES")
        GEOGRAPHY_DIVISION_HRVATSKA_STATES=["Bjelovar-Bilogora","Brod-Posavina","Dubrovnik-Neretva","Istria","Krapina-Zagorje","Karlovac","Koprivnica-Krizevci","Lika-Senj","Medimurje","Osijek-Baranja","Primorje-Gorski Kotar","Pozega-Slavonia","Sibenik-Knin","Split-Dalmatia","Sisak-Moslavina","Varazdin","Virovitica-Podravina","Vukovar-Srijem","Zadar","Zagreb"] unless const_defined?("GEOGRAPHY_DIVISION_HRVATSKA_STATES")
        GEOGRAPHY_DIVISION_HUNGARY_STATES=["Bacs-Kiskun","Bkaranya","Bekes","Borsod-Abauj-Zemplen","Csongrad","Fejer","Gyor-Moson-Sopron","Hajdu-Bihar","Heves","Jasz-Nagykun-Szolnok","Komarom-Esztergom","Nograd","Pest","Somogy","Szabolcs-Szatmar-Bereg","Tolna","Vas","Veszprem","Zalak"] unless const_defined?("GEOGRAPHY_DIVISION_HUNGARY_STATES")        
        #I
        GEOGRAPHY_DIVISION_ICELAND_STATES=["Austurland","Hofuoborgarsvaeoi","Norourland vestra","Norourland eystra","Suournes","Suourland","Vesturland","Vestfiroir"] unless const_defined?("GEOGRAPHY_DIVISION_ICELAND_STATES")
        GEOGRAPHY_DIVISION_INDIA_STATES=["Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Orissa","Punjab","Rajasthan","Sikkim","Tamil Nadu","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Andaman and Nicobar Islands","Chandigarh","Dadra and Nagar Haveli","Daman and Diu","Lakshadweep","Delhi","Puducherry"] unless const_defined?("GEOGRAPHY_DIVISION_INDIA_STATES")
        GEOGRAPHY_DIVISION_INDONESIA_STATES=["Bakli","Bangka-Belitung","Banten","Bengkulu","Central Java","Central Kalimantan (C.Borneo)","Central Sulawesi","East Java","East Kalimantan (E.Borneo)","Tenggara","Gorontalo","Jakarta Special Capital Region","Jambi","Lampung","Maluku (Moluccas)","Nanggroe Aceh Darussalam","North Maluku (N.Moluccas)","North Sulawesi","North Sumatra","Papua","Riau","Riau Islands","South East Sulawesi","South Kalimantan (S.Borneo)","South Sulawesi","South Sumatra","West Java","West Kalimantan (W.Borneo)","West Nusa Tenggara","West Papua","West Sulawesi","West Sumatra","Yogyakarta Special Region"] unless const_defined?("GEOGRAPHY_DIVISION_INDONESIA_STATES")
        GEOGRAPHY_DIVISION_IRAN_STATES=["Ardabil","Azarbaijan East","Azarbaijan West","Bushehr","Chahar Mahaal and Bakhtiari","Fars","Gilan","Golestan","Hamadan","Hormaozgan","Iiam","Isfahan","Kerman","Kermanshah","Khorasan-North","Khorasan","Kohgiluyeh and Boyer-Ahmad","Kurdistan","Lorestan","Markaxi","Mazandaran","Qazvin","Qom","Razavi","Khorasan","South","Khuzestan","Semanan","Sistan and Baluchistan","Teharan","Yazd","Zanjan"] unless const_defined?("GEOGRAPHY_DIVISION_IRAN_STATES")
        GEOGRAPHY_DIVISION_IRAQ_STATES=["Arbil","Ai Anbar","An Najaf","Al Basrah","Al-Qadisiyyah","Al Muthanna","Baghdad","Babil","Diyala","Dhi Qar","Karbala","Karbala","Kirkuk","Maysan","Ninawa","Dahuk","Sulaymaniyah","Salah ad Din","Wasit"] unless const_defined?("GEOGRAPHY_DIVISION_IRAQ_STATES")
        GEOGRAPHY_DIVISION_IRELAND_STATES=["Connacht","Leinster","Munster","Ulster"] unless const_defined?("GEOGRAPHY_DIVISION_IRELAND_STATES")
        GEOGRAPHY_DIVISION_ISLEOFMAN_STATES=["Isle of Man","Calf of Man","St.Michael's Isle","St. Patrick's Isle","Kitterland","St. Mary's Isle","Chicken Rock"] unless const_defined?("GEOGRAPHY_DIVISION_ISLEOFMAN_STATES")
        GEOGRAPHY_DIVISION_ISRAEL_STATES=["Center Israel","Haifa","Jerusalem","North Israel","South Israel","Tel Aviv"] unless const_defined?("GEOGRAPHY_DIVISION_ISRAEL_STATES")
        GEOGRAPHY_DIVISION_ITALY_STATES=["Abruzzo","Aosta Valley","Apulia","Basilicata","Calabria","Campania","Emilia-Romagna","Friuli-Venezia Giulia","Lazio","Liguria","Lombardy","Marche","Molise","Piedmont","Sardinia","Sicity","Tuscany","Trentino-Alto Adige","Umbria","Veneto"] unless const_defined?("GEOGRAPHY_DIVISION_ITALY_STATES")
        #J
        GEOGRAPHY_DIVISION_JAMAICA_STATES=["Clarendon","Hanover","Manchester","Portland","Saint Ann","Saint Catherine","Saint Mary","Kingston","Saint Andrew","Saint Thomas","Saint Elizabeth","Saint James","Trelawny","Westmoreland"] unless const_defined?("GEOGRAPHY_DIVISION_JAMAICA_STATES")
        GEOGRAPHY_DIVISION_JAPAN_STATES=["Aichi","Akita","Aomori","Chiba","Ehime","Fukui","Fukuoka","Fukushima","Gifu","Gunma","Hiroshima","Hokkaido","Hyogo","Ibaraki","Ishikawa","Iwate","Kagawa","Kagoshima","Kanagawa","Kochi","Kumamoto","Kyoto","Mie","Miyagi","Miyazaki","Nagano","Nagasaki","Nara","Niigata","Oita","Okayama","Okinawa","Osaka","Saga","Saitama","Saitama","Shiga","Shimane","Shizuoka","Tochigi","Tokushima","Tokyo","Tottori","Toyama","Wakayama","Yamagata","Yamaguchi","Yamanashi"] unless const_defined?("GEOGRAPHY_DIVISION_JAPAN_STATES")
        GEOGRAPHY_DIVISION_JORDAN_STATES=["Ajlun","Amman","Aqaba","Baliqa","Irbid","Jerash","Karak","Ma'an","Madaba","Mafraq","Tafilah","Zarqa"] unless const_defined?("GEOGRAPHY_DIVISION_JORDAN_STATES")
        #K
        GEOGRAPHY_DIVISION_KAZAKHSTAN_STATES=["Akmola","Aktobe","Almaty","Almaty Province","Astana","Atyrau","Baikonur","East Kazakhstan","Karagandy","Kostanay","Kyzylorda","Mangystau","North Kazakhstan","Paviodar","South Kazakhstan","West Kazakhstan","Zhambyl"] unless const_defined?("GEOGRAPHY_DIVISION_KAZAKHSTAN_STATES")
        GEOGRAPHY_DIVISION_KENYA_STATES=["Central Kenya","Coast","Eastern Kenya","Nairobi","North Eastern","Nyanza","Rift Valley","Western"] unless const_defined?("GEOGRAPHY_DIVISION_KENYA_STATES")
        GEOGRAPHY_DIVISION_KIRIBATI_STATES=["Banaba","Central Gilberts","Line Islands","Northern Gilberts","Southern Gilberts","Tarawa Atoll"] unless const_defined?("GEOGRAPHY_DIVISION_KIRIBATI_STATES")
        GEOGRAPHY_DIVISION_NORTHKOREA_STATES=["Chagang","North Hamgyong","South Hamgyong","North Hwanghae","South Hawanghae","Kangwon","Noth  P'yongan","South P'yongan","Ryanggang"] unless const_defined?("GEOGRAPHY_DIVISION_NORTHKOREA_STATES")
        GEOGRAPHY_DIVISION_SOUTHKOREA_STATES=["Gangwon","Gyeonggi","Jeju","North Chungcheong","North Gyeongsang","North Jeolla","South Chungcheong","South Gyeongsang","South Jeolla"] unless const_defined?("GEOGRAPHY_DIVISION_SOUTHKOREA_STATES")
        GEOGRAPHY_DIVISION_KUWAIT_STATES=["Al Ahmadi","Al Farwaniyah","Al Asimah","Al Jahra","Hawalli","Mubarak Al-Kabeer"] unless const_defined?("GEOGRAPHY_DIVISION_KUWAIT_STATES")
        GEOGRAPHY_DIVISION_KYRGYZSTAN_STATES=["Batken","Chui","Issyk-Kul","Jalal-Abad","Naryn","Osh","Talas"] unless const_defined?("GEOGRAPHY_DIVISION_KYRGYZSTAN_STATES")
        #L
        GEOGRAPHY_DIVISION_LAOS_STATES=["Attapu","Bokeo","Bolikhamxai","Champasak","Houaphan","Khammouan","Loung Namtha","Louagphabang","Oudomxai","Phongsali","Salavan","Savannakhet","Vientiane Capital","Vientiane Province","Xaignabouli","Xaisomboun","Xekong","Xiangkhoang"] unless const_defined?("GEOGRAPHY_DIVISION_LAOS_STATES")
        GEOGRAPHY_DIVISION_LATVIA_STATES=["Aizkraukle","Aluksne","Balvi","Bauska","Cesis","Daugavpils","Dobele","Gulbene","Jekabpils","Jelgava","Kraslava","Kuldiga","Liepaja","Limbazi","Ludza","Madona","Ogre","Preili","Rezekne","Riga","Saldus","Talsi","Tukums","Valka","Valmiera","Ventspils"] unless const_defined?("GEOGRAPHY_DIVISION_LATVIA_STATES")
        GEOGRAPHY_DIVISION_LEBANON_STATES=["Beirut","Beqaa","North","Nabatiyeh","Mount Lebanon","South"] unless const_defined?("GEOGRAPHY_DIVISION_LEBANON_STATES")
        GEOGRAPHY_DIVISION_LESOTHO_STATES=["Berea","Butha-Buthe","Leribe","Mafeteng","Maseru","Mohale's Hoek","Mokhotlong","Qacha's Nek","Quthing","Thaba-Tseka"] unless const_defined?("GEOGRAPHY_DIVISION_LESOTHO_STATES")
        GEOGRAPHY_DIVISION_LIBERIA_STATES=["Bomi","Bong","Gbarpolu","Grand Bassa","Grand Cape Mount","Grand Gedeh","Grand Kru","Lofa","Margibi","Maryland","Montserrado","Nimba","River Cess","River Gee","Sinoe"] unless const_defined?("GEOGRAPHY_DIVISION_LIBERIA_STATES")
        GEOGRAPHY_DIVISION_LIBYA_STATES=["An Nuqat al Khams","Al Butnan","Al Jabal al Akhadar","Al Marj","Al Murgub","Al Jfara","Al jufrah","Al Wahat","Al kufrah","Az Zawiyah","Al Jabal al Gharbi","Benghazi","Darnah","Ghat","Murzuq","Misratah","Nalut","Sabha","Surt","Tarabulus","Tarabulus","Wadi Al Hayaa","Wadi Al Shatii"] unless const_defined?("GEOGRAPHY_DIVISION_LIBYA_STATES")
        GEOGRAPHY_DIVISION_LIECHTENSTEIN_STATES=["Balzers","Eschen","Gamprin","Mauren","Planken","Ruggell","Schaan","Schellenberg","Triesen","Triesenberg Malbun","Vaduz"] unless const_defined?("GEOGRAPHY_DIVISION_LIECHTENSTIEN_STATES")
        GEOGRAPHY_DIVISION_LITHUANIA_STATES=["Alytus","Kaunas","Klaipeda","Marijampole","Panevezys","Siauliai","Taurage","Telsiai","Utena","Vilnius"] unless const_defined?("GEOGRAPHY_DIVISION_LITHUANIA_STATES")
        GEOGRAPHY_DIVISION_LUXEMBOURG_STATES=["Diekirch","Grevenmacher","Luxembourg"] unless const_defined?("GEOGRAPHY_DIVISION_LUXEMBOURG_STATES")
        #M
        GEOGRAPHY_DIVISION_MACAU_STATES=["Macau Peninsula","Cotai","Taipa","Coloane"] unless const_defined?("GEOGRAPHY_DIVISION_MACAU_STATES")
        GEOGRAPHY_DIVISION_MACEDONIA_STATES=["Eastern","Northeastern","Pelagonia","Polog","Southwestern","Skopje","Southeastern","Vardar"] unless const_defined?("GEOGRAPHY_DIVISION_MACEDONIA_STATES")
        GEOGRAPHY_DIVISION_MADAGASCAR_STATES=["Antananarivo","Antsiranana","Fianarantsoa","Mahajanga","Toamasina","Toliara"] unless const_defined?("GEOGRAPHY_DIVISION_MADAGASCAR_STATES")
        GEOGRAPHY_DIVISION_MALAWI_STATES=["Central","Northern","Southern"] unless const_defined?("GEOGRAPHY_DIVISION_MALAWI_STATES")
        GEOGRAPHY_DIVISION_MALAYSIA_STATES=["Johor","Kedah","Kelantan","Kuala Lumpur","Labuan","Melaka","Negeri","Negeri Sembilan","Pahang","Perak","Perlis","Pulau Pinang","Putrajaya","Sabah","Selangor","Sarawak","Terengganu"] unless const_defined?("GEOGRAPHY_DIVISION_MALAYSIA_STATES")
        GEOGRAPHY_DIVISION_MALDIVES_STATES=["Mathi-Uthuru","Medha-Uthuru","Medu","Mathi-Dhekunu","Medhu-Dhekunu","Dhekunu"] unless const_defined?("GEOGRAPHY_DIVISION_MALDIVES_STATES")
        GEOGRAPHY_DIVISION_MALI_STATES=["Gao","Kayes","Kidal","Koulikoro","Mopti","Segou","Sikasso","Tombouctou"] unless const_defined?("GEOGRAPHY_DIVISION_MALI_STATES")
        GEOGRAPHY_DIVISION_MALTA_STATES=["Barbaganni Rock","Comino","Cominotto","Delmarva","Filfla","Fessej Rock","Fungus Rock","Ghallis Rock","Gozo","Halfa Rock","Large Blue Lagoon Rocks","Island of St. paul","Malta Island","Manoel Island","Mistra Rocks","Qawra Point","Small Blue Lagoon Rocks","Sala Rock","Tac-Cawl Rock","Xrob l-Ghagin Rock"] unless const_defined?("GEOGRAPHY_DIVISION_MALTA_STATES")
        GEOGRAPHY_DIVISION_MARSHALLISLANDS_STATES=["Ailinglaplap Atoll","Ailinginae Atoll","Ailuk Atoll","Arno Atoll","Aur Atoll","Bikar Atoll","Bikini Atoll","Bokak Atoll","Erikub Atoll","Ebon Atoll","Enewetak Atoll","Jemo island","Jabat Island","Jaluit Atoll","Kili Island","Kwajalein Atoll","Lae Atoll","Lib Island","Likiep Atoll","Majuro Atoll","Maloelap Atoll","Mejit Island","Mili Atoll","Nadikdik Atoll","Namdrik Atoll","Rongerik Atoll","Rongelap Atoll","Toke Atoll","Ujelang Atoll","Ujae Atoll","Utirik Atoll","Wotho Atoll","Wotje Atoll"] unless const_defined?("GEOGRAPHY_DIVISION_MARSHALLISLANDS_STATES")
        GEOGRAPHY_DIVISION_MARTINIQUE_STATES=["Arrondissement of Fort-de-France","Arrondissement of La Trinite","Arrondissement of Le Marin","Arrondissement of Saint-Pierre"] unless const_defined?("GEOGRAPHY_DIVISION_MARTINIQUE_STATES")
        GEOGRAPHY_DIVISION_MAURITANIA_STATES=["Adrar","Assaba","Brakna","Dakhlet Nouadhibou","Gorgol","Guidimaka","Hodh Ech Chargui","Hodh El Gharbi","Inchiri","Nouakchott","Tagant","Tiris Zemmour","Trarza"] unless const_defined?("GEOGRAPHY_DIVISION_MAURITANIA_STATES")
        GEOGRAPHY_DIVISION_MAURITIUS_STATES=["Black River","Flacq","Grand Port","Moka","Pamplemousses","Plaines Wilhems","Port Louis","Riviere du Rempart","Savanne"] unless const_defined?("GEOGRAPHY_DIVISION_MAURITIUS_STATES")
        GEOGRAPHY_DIVISION_MAYOTTE_STATES=["Acoua","Bandrele","Boueni","Bandraboua","Chirongui","Chiconi","Dzaoudzi","Dembeni","Koungou","Kani-Keli","Mamoudzou","Mtsamboro","M'Tsangamouji","Ouangani","Pamandzi","Sada","Tsingoni"] unless const_defined?("GEOGRAPHY_DIVISION_MAYOTTE_STATES")
        GEOGRAPHY_DIVISION_MEXICO_STATES=["Aguascalientes","Baja California","Baja California Sur","Chihuahua","Colima","Campeche","Coahuila","Chiapas","Durango","Guerrero","Guanajuato","Hidalgo","Jalisco","Michoacan","Morelos","Mexico State","Nayarit","Nuevo Leon","Oaxaca","Puebla","Quintana Roo","Queretaro","Sinaloa","San Luis Potosi","Sonora","Tabasco","Tlaxcala","Tamaulipas","Veracruz","Yucatan","Zacatecas"] unless const_defined?("GEOGRAPHY_DIVISION_MEXICO_STATES")
        GEOGRAPHY_DIVISION_MICRONESIA_STATES=["Federated States of Micronesia","Guam","Kiribati","Marshall Islands","Nauru","Northern Mariana Islands","Palau","Wake Island"] unless const_defined?("GEOGRAPHY_DIVISION_MICRONESIA_STATES")
        GEOGRAPHY_DIVISION_MOLDOVA_STATES=["Aneni Noi","Basarabeasca","Briceni","Cahul","Cantemir","Calarasi","Causeni","Cimislia","Criuleni","Donduseni","Drochia","Dubasari","Edinet","Falesti","Floresti","Glodeni","Hincesti","Ialoveni","Leova","Nisporeni","Ocnita","Orhei","Rezina","Riscani","Singerei","Soroca","Straseni","Soldansti","Stefan Voda","Taraclia","Telenesti","Ungheni"] unless const_defined?("GEOGRAPHY_DIVISION_MOLDOVA_STATES")
        GEOGRAPHY_DIVISION_MONACO_STATES=["Fontvieille","La Rousse/Saint Roman","Larvotto/Bas Moulins","La Condamine","La Colle","Les Revoires","Le Portier","Monte Carlo/Spelugues","Monaco-Ville","Moneghetti/Bd de Belgique","Saint Michel"] unless const_defined?("GEOGRAPHY_DIVISION_MONACO_STATES")
        GEOGRAPHY_DIVISION_MONGOLIA_STATES=["Arkhangai","Bayan-Olgii","Bayankhongor","Bulgan","Darkhan-Uul","Dornogovi","Dundgovi","Govi-Altai","Govisumber","Khentii","Khovd","Khovsgol","Omnogovi","Orkhon","Ovorkhangai","Selenge","Sukhbaatar","Tov","Uvs","Zavkhan"] unless const_defined?("GEOGRAPHY_DIVISION_MONGOLIA_STATES")
        GEOGRAPHY_DIVISION_MONTENEGRO_STATES=["Andrijevica","Bar","Berane","Bijelo Polje","Budva","Cetinje","Danilovgrad","Herceg Novi","Kolasin","Kotor","Mojkovac","Niksic","Plav","Pluzine","Pljevlja","Podgorica","Golubovci","Tuzi","Rozaje","Savnik","Tivat","Ulcinj","Zabljak"] unless const_defined?("GEOGRAPHY_DIVISION_MONTENEGRO_STATES")
        GEOGRAPHY_DIVISION_MONTSERRAT_STATES=["Saint Anthony","Saint Georges","Saint Peter"] unless const_defined?("GEOGRAPHY_DIVISION_MONTSERRAT_STATES")
        GEOGRAPHY_DIVISION_MOROCCO_STATES=["Chaouia-Ouardigha","Doukkala-Abda","Fes-Boulemane","Gharb-Chrarda-Beni Hssen","Greater Casablanca","Guelmim-Es Semara","Laayoune-Boujdour-Sakia El Hamra","Marrakech-Tensift-El Haouz","Meknes-Tafilalet","Oriental","Oued Ed-Dahab-Lagouira","Rabat-Sale-Zemmour-Zaer","Souss-Massa-Draa","Tadla-Azilal","Tangier-Tetouan","Taza-Al  Hoceima-Taounate"] unless const_defined?("GEOGRAPHY_DIVISION_MOROCCO_STATES")
        GEOGRAPHY_DIVISION_MOZAMBIQUE_STATES=["Cabo Delgado","Gaza","Inhambane","Manica","Maputo","Nampula","Niassa","Sofala","Tete","Zambezia"] unless const_defined?("GEOGRAPHY_DIVISION_MOZAMBIQUE_STATES")
        GEOGRAPHY_DIVISION_MYANMAR_STATES=["Chin","Kachin","Kayin","Kayah","Mon","Rakhine","Shan"] unless const_defined?("GEOGRAPHY_DIVISION_MYANMAR_STATES")
        #N
        GEOGRAPHY_DIVISION_NAMIBIA_STATES=["Caprivi","Erongo","Hardap","Karas","Kavango","Khomas","Kunene","Ohangwena","Omaheke","Omusati","Oshana","Oshikoto","Otjozondjupa"] unless const_defined?("GEOGRAPHY_DIVISION_NAMIBIA_STATES")
        GEOGRAPHY_DIVISION_NAURU_STATES=["Aiwo","Anabar","Anetan","Anibare","Baiti","Boe","Buada","Denigomodu","Ewa","Ijuw","Meneng","Nibok","Uaboe","Yaren"] unless const_defined?("GEOGRAPHY_DIVISION_NAURU_STATES")
        GEOGRAPHY_DIVISION_NEPAL_STATES=["Bagmati","Bheri","Dhawalagiri","Gandaki","Janakpur","Karnali","Kosi","Lumbini","Mahakali","Mechi","Narayani","Rapti","Sagarmatha","Seti"] unless const_defined?("GEOGRAPHY_DIVISION_NEPAL_STATES")
        GEOGRAPHY_DIVISION_NETHERLANDS_STATES=["Drenthe","Flevoland","Friesland","Gelderland","Groningen","Limburg","North Brabant","North Holland","Overijssel","South Holland","Utrecht","Zealand"] unless const_defined?("GEOGRAPHY_DIVISION_NETHERLANDS_STATES")
        GEOGRAPHY_DIVISION_NETHERLANDSANTILLES_STATES=["Bonaire","Curacao","Saba","Sint Eustatius","Sint Maarten"] unless const_defined?("GEOGRAPHY_DIVISION_NETHERLANDSANTILLES_STATES")
        GEOGRAPHY_DIVISION_NEWCALEDONIA_STATES=["Loyalty Islands","North","South"] unless const_defined?("GEOGRAPHY_DIVISION_NEWCALEDONIA_STATES")
        GEOGRAPHY_DIVISION_NEWZEALAND_STATES=["Auckland","Bay of Plenty","Canterbury","East Cape","Hawke's Bay","Manawatu-Wanganui","Marlborough","Nelson","Northland","Otago","Southland","Tasman","Taranaki","West Coast","Waikato","Wellington"] unless const_defined?("GEOGRAPHY_DIVISION_NEWZEALAND_STATES")
        GEOGRAPHY_DIVISION_NICARAGUA_STATES=["Boaco","Carazo","Chinandega","Chontales","Esteli","Granada","Jinotega","Leon","Madriz","Managua","Masaya","Matagalpa","Nueva Segovia","Rivas","Rio San Juan","Region Autonoma del Atlantico Norte","Region Autonoma del Atlantico Sur"] unless const_defined?("GEOGRAPHY_DIVISION_NICARAGUA_STATES")
        GEOGRAPHY_DIVISION_NIGER_STATES=["Agadez","Diffa","Dosso","Maradi","Tahoua","Tillaberi","Zinder"] unless const_defined?("GEOGRAPHY_DIVISION_NIGER_STATES")
        GEOGRAPHY_DIVISION_NIGERIA_STATES=["Abia","Adamawa","Akawa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara"] unless const_defined?("GEOGRAPHY_DIVISION_NIGERIA_STATES")
        GEOGRAPHY_DIVISION_NIUE_STATES=["Alofi North","Alofi South","Avatele","Hikutavake","Hakupu","Lakepa","Liku","Makefu","Mutalau Namukulu","Tamakautoga","Toi","Tuapa","Vaiea"] unless const_defined?("GEOGRAPHY_DIVISION_NIUE_STATES")
        GEOGRAPHY_DIVISION_NORFOLKISLAND_STATES=[] unless const_defined?("GEOGRAPHY_DIVISION_NORFOLKISLAND_STATES")
        GEOGRAPHY_DIVISION_NORTHERNMARIANAISLANDS_STATES=["Asuncion","Aguijan","Anatahan","Agrihan","Alamagan","Farallon de Pajaros","Farallon de Medinilla","Guguan","Maug Island","Pagan","Rota","Sarigan","Saipan","Tinian","Zealandia Bank"] unless const_defined?("GEOGRAPHY_DIVISION_NORTHERNMARIANAISLANDS_STATES")
        GEOGRAPHY_DIVISION_NORWAY_STATES=["Akershus","Aust-Agder","Buskerud","Finnmark","Hedmark","Hordaland","More og Romsdal","Nord- Trondelag","Nordland","Oppland","Oslo","Ostfold","Rogaland","Sogn og Fjordane","Sor-Trondelag","Telemark","Troms","Vest-Agder","Vestfold"] unless const_defined?("GEOGRAPHY_DIVISION_NORWAY_STATES")
        #O
        GEOGRAPHY_DIVISION_OMAN_STATES=["Ai Buraymi","Dhofar","Muscat","Musandam"] unless const_defined?("GEOGRAPHY_DIVISION_OMAN_STATES")
        #P
        GEOGRAPHY_DIVISION_PAKISTAN_STATES=["Balochistan","North-West Frontier Province","Punjab","Sindh","Azad Jammu and Kashmir","Federally Administered Tribal Areas","Islamabad Capital Territory","Northern Areas"] unless const_defined?("GEOGRAPHY_DIVISION_PAKISTAN_STATES")
        GEOGRAPHY_DIVISION_PALAU_STATES=["Aimeliik","Airai","Angaur","Hatohobei","Kayangel","Koror","Melekeok","Ngaraard","Ngarchelong","Ngardmau","Ngaremlengui","Ngatpang","Ngchesar","Ngiwal","Peleliu","Sonsorol"] unless const_defined?("GEOGRAPHY_DIVISION_PALAU_STATES")
        GEOGRAPHY_DIVISION_PALESTINIANTERRITORIES_STATES=["West Bank","Gaza"] unless const_defined?("GEOGRAPHY_DIVISION_PALESTINIANTERRITORES_STATES")
        GEOGRAPHY_DIVISION_PANAMA_STATES=["Bocas del Toro","Chiriqui","Cocle","Colon","Darien","Herrera","Los Santos","Panama","Veraguas"] unless const_defined?("GEOGRAPHY_DIVISION_PANAMA_STATES")
        GEOGRAPHY_DIVISION_PAPUANEWGUINEA_STATES=["Autonomous Region of Bougainville","Central","Chimbu","Eastern Highlands","East New Britain","East Sepik","Enga","Gulf","Madang","Manus","Milne Bay","Morobe","National Capital District","New Ireland","Northern(Oro Province)","Southern Highlands","Western(Fly)","Western Highlands","West New Britain","Sandaun (West Sepik)"] unless const_defined?("GEOGRAPHY_DIVISION_PAPUANEWGUINEA_STATES")
        GEOGRAPHY_DIVISION_PARAGUAY_STATES=["Alto Paraguay","Alto Parana","Amambay","Boqueron","Caaguazu","Caazapa","Canindeyu","Central","Distrito Capital"] unless const_defined?("GEOGRAPHY_DIVISION_PARAGUAY_STATES")
        GEOGRAPHY_DIVISION_PERU_STATES=["Amazonas","Ancash","Apurimac","Arequipa","Ayacucho","Cajamarca","Callao","Cusco","Huancavelica","Huanuco","Ica","Junin","La Libertad","Lambayeque","Lima","Loreto","Madre de Diios","Moquegua","Pasco","Piura","Puno","San Martin","Tacan","Tumbes","Ucayali"] unless const_defined?("GEOGRAPHY_DIVISION_PERU_STATES")
        GEOGRAPHY_DIVISION_PHILIPPINES_STATES=["Autonomous Region in Muslim Mindanao","Bicol Region","Central Visayas","Cagayan Valley","Central Luzon","Calabarzon","Caraga","Cordillera Administrative Region","Davao Region","Eastern Visayas","Ilocos Region","Mimaropa","Northern Mindanao","National Capital Region","Soccsksargen","Western Visayas","Zamboanga Peninsula"] unless const_defined?("GEOGRAPHY_DIVISION_PHILIPPINIES_STATES")
        GEOGRAPHY_DIVISION_PITCAIRNISLAND_STATES=["Ducie","Henderson","Oeno"] unless const_defined?("GEOGRAPHY_DIVISION_PITCAIRNISLAND_STATES")
        GEOGRAPHY_DIVISION_POLAND_STATES=["Greater Poland","Kuyavian-Pomeranian","Lesser Polan","Lodz","Lower Silesian","Lublin","Lubusz","Masovian","Opole","Podlaskie","Pomeranian","Silesian","Subcarpathian","Swietokrzyskie","Warmian-Masurian","West Pomeranian"] unless const_defined?("GEOGRAPHY_DIVISION_POLAND_STATES")
        GEOGRAPHY_DIVISION_PORTUGAL_STATES=["Acores","Alentejo","Algarve","Centro","Lisboa","Madeira","Norte"] unless const_defined?("GEOGRAPHY_DIVISION_PORTUGAL_STATES")
        GEOGRAPHY_DIVISION_PUERTORICO_STATES=["Adjuntas","Aguada","Aguadilla","Aguas Buenas","Aibonito","Anasco","Arecibo","Arroyo","Barceloneta","Barranquitas","Bayamon","Cabo Rojo","Caguas","Camuy","Canovanas","Carolina","Catano","Cayey","Ceiba","Ciales","Cidra","Coamo","Comerio","Corozal","Culebra","Dorado","Fajardo","Florida","Guanica","Guayama","Guayanilla","Guaynabo","Gurabo","Hatillo","Hormigueros","Humacao","Isabela","Jayuya","Juana Diaz","Juncos","Lajas","Lares","Las Marias","Las Piedras","Loiza","Luquillo","Manati","Maricao","Maunabo","Mayaguez","Moca","Morovis","Naguabo","Naranjito","Orocovis","Patillas","Penuelas","Ponce","Quebradillas","Rincon","Rio Grande","Sabana Grande","Salinas","San German","San Juan","San Lorenzo","San Sebastian","Santa Isabel","Toa Alta","Toa Baja","Trujillo Alto","Utuado","Vega Alta","Vega Baja","Vieques","Villalba","Yabucoa","Yauco"] unless const_defined?("GEOGRAPHY_DIVISION_PUERTORICO_STATES")
        #Q
        GEOGRAPHY_DIVISION_QATAR_STATES=["Ad Dawhah","Al Ghuwariyah","Al Jumaliyah","Al Khawr","Al Wakrah","Ar Rayyan","Ash Shamal","Jariyan al Batnah","Mesaieed","Umm Salal"] unless const_defined?("GEOGRAPHY_DIVISION_QATAR_STATES")
        #R
        GEOGRAPHY_DIVISION_REUNION_STATES=["Arrondissements of Saint-Denis","Arrondissements of Saint- Benoit","Arrondissements of Saint-Paul","Arrondissements of Saint-Pierre"] unless const_defined?("GEOGRAPHY_DIVISION_REUNION_STATES")
        GEOGRAPHY_DIVISION_ROMANIA_STATES=["Alba","Arad","Arad","Bacau","Bihor","Bistrita-Nasaud","Botosani","Brasov","Braila","Buzau","Bucuresti ","Caras-Severin","Calarasi","Cluj","Constanta","Covasna","Dambovita","Dolj","Galati","Giurgiu","Gorj","Harghita","Hunedoara","Ialomita","Iasi","Ilfov","Maramures","Mehedinti","Mures","Neamt","Olt","Prahova","Satu Mare","Salaj","Sibiu","Suceava","Teleorman","Timis","Tulcea","Vaslui","Valcea","Vrancea"] unless const_defined?("GEOGRAPHY_DIVISION_ROMANIA_STATES")
        GEOGRAPHY_DIVISION_RUSSIA_STATES=["Amur","Arkhangelsk","Astrakhan","Belgorod","Bryansk","Chelyabinsk","Irkutsk","Ivanovo","Kaliningrad","Kaluga","Kemerovo","Kirov","Kostroma","Kurgan","Kursk","Leningrad","Lipetsk","Magadan","Moscow","Murmansk","Nizhny Novgorod","Novosibirsk","Omsk","Orenburg","Oryol","Penza","Pskov","Rostov","Ryazan","Sakhalin","Samara","Saratov","Smolensk","Sverdlovsk","Tomsk","Tver","Tula","Tyumen","Ulyanovsk","Vladimir","Volgograd","Vologda","Voronezh","Yaroslavl"] unless const_defined?("GEOGRAPHY_DIVISION_RUSSIA_STATES")
        GEOGRAPHY_DIVISION_RWANDA_STATES=["East","North","South","West","Kigal"] unless const_defined?("GEOGRAPHY_DIVISION_RWANDA_STATES")
        #S
        GEOGRAPHY_DIVISION_SAMOA_STATES=["Aana","Aiga-i-le-Tai","Atua","Savaii","Faasaleleaga","Gagaemauga","Gagaifomauga","Palauli","Satupaitea","Tuamasaga","Vaa-o-Fonoti","Vaisigano"] unless const_defined?("GEOGRAPHY_DIVISION_SAMOA_STATES")
        GEOGRAPHY_DIVISION_SANMARINO_STATES=["Ca Berlone","Ca Chiavello","Ca Giannino","Ca Melone","Ca Ragni","Ca Rigo","Cailungo","Caladino","Calligaria","Canepa","Capanne","Casole","Castellaro","Cerbaiola","Cinque Vie","Confine","Corianino","Crociale","Dogana","Falciano","Fiorina","Galavotto","Gualdicciolo","La Serra","Lesignano","Molarini","Montalbo","Monte Pulito","Murata","Pianacci","Piandivello","Poggio Casalino","Poggio Chiesanuova","Ponte Mellini","Rovereta","San Giovanni sotto le Penne","Santa Mustiola","Spaccio Giannoni","Teglio","Torraccia","Valdragone","Valgiurata","Ventoso"] unless const_defined?("GEOGRAPHY_DIVISION_SANMARINO_STATES")
        GEOGRAPHY_DIVISION_SAOTOMEANDPRINCIPE_STATES=["Principe","Sao Tome"] unless const_defined?("GEOGRAPHY_DIVISION_SAOTOMEANDPRIINCIPE_STATES")
        GEOGRAPHY_DIVISION_SAUDIARABIA_STATES=["Al Bahah","Al Jawf","Medina","Al Qasim","Hail","Asir","Al Riyadh","Eastern Province","Jizan","Makkah","Najran","Northern Border","Tabuk"] unless const_defined?("GEOGRAPHY_DIVISION_SAUDIARABIA_STATES")
        GEOGRAPHY_DIVISION_SENEGAL_STATES=["Dakar Region","Diourbel Region","Fatick Region","Kaffrine Region","Kaolack Region","Kedougou Region","Kolda Region","Louga Region","Matam Region","Saint-Louis Region","Sedhiou Region","Tambacounda Region","Thies Region","Ziguinchor Region"] unless const_defined?("GEOGRAPHY_DIVISION_SENEGAL_STATES")
        GEOGRAPHY_DIVISION_SERBIA_STATES=["Kosovo","Vojvodina","Serbia"] unless const_defined?("GEOGRAPHY_DIVISION_SERBIA_STATES")
        GEOGRAPHY_DIVISION_SEYCHELLES_STATES=["Anse Boileau","Anse aux Pins","Anse Etoile","Au Cap","Anse Royale","Baie Sainte Anne","Bel Air","Baie Lazare","Beau Vallon","Bel Ombre","Cascade","Grand'Anse Praslin","Glacis","Grand'Anse Mahe","La Digue","La Riviere Anglaise","Les Mamelles","Mont Buxton","Mont Fleuri","Plaisance","Pointe La Rue","Port Glaud Takamaka","Roche Caiman","Saint Louis"] unless const_defined?("GEOGRAPHY_DIVISION_SEYCHELLES_STATES")
        GEOGRAPHY_DIVISION_SIERRALEONE_STATES=["Eastern Province","Northern Province","Southern Province"] unless const_defined?("GEOGRAPHY_DIVISION_SIERRALEONE_STATES")
        GEOGRAPHY_DIVISION_SLOVAKIA_STATES=["Bratislava Region","Banska Bystrica Region","Kosice Region","Nitra Region","Presov Region","Trnava Region","Trencin Region","Zilina Region"] unless const_defined?("GEOGRAPHY_DIVISION_SLOVAKIA_STATES")
        GEOGRAPHY_DIVISION_SLOVENIA_STATES=["Carinthia","Goriska","Inner Carniola","Lower Styria","Lower Carniola","Prekmurje","Slovenian Istria","Upper Carniola"]  unless const_defined?("GEOGRAPHY_DIVISION_SLOVENIA_STATES")
        GEOGRAPHY_DIVISION_SOLOMONISLANDS_STATES=["Central","Choiseul","Guadalcanal","Honiara","Town","Isabel","Makira-Ulawa","Malaita","Rennell and Bellona","Temotu","Western"] unless const_defined?("GEOGRAPHY_DIVISION_SOLOMONISLANDS_STATES")
        GEOGRAPHY_DIVISION_SOMALIA_STATES=["Awdal","Bakool","Banaadir","Bari","Bay","Galguduud","Gedo","Hiiraan","Jubbada Dhexe","Jubbada Hoose","Mudug","Nugaal","Sanaag","Shabeellaha Dhexe","Shabeellaha Hoose","Sool","Togdheer","Woqooyi Galbeed"] unless const_defined?("GEOGRAPHY_DIVISION_SOMALIA_STATES")
        GEOGRAPHY_DIVISION_SOUTHAFRICA_STATES=["Eastern Cape","Free State","Gauteng","KwaZulu-Natal","Limpopo","Mpumalanga","Northern Cape","North West","Western Cape"] unless const_defined?("GEOGRAPHY_DIVISION_SOUTHAFRICA_STATES")
        GEOGRAPHY_DIVISION_SOUTHGEORGIAANDTHESOUTHSANDWICHISLANDS_STATES=["Annenkov Island","Bird Island","Cooper Island","Grass Island","Pickersgill Islands","Trinity Island","Welcome Islands","Willis Islands"] unless const_defined?("GEOGRAPHY_DIVISION_SOUTHGEORGIAANDTHESOUTHSANDWICHISLANDS_STATES")
        GEOGRAPHY_DIVISION_SPAIN_STATES=["Alava","Albacete","Alicante","Almeria","Asturias","Avila","Badajoz","Baleares","Barcelona","Vizcaya","Burgos","Caceres","Cadiz","Cantabria","Castellon","CiudadReal","Cordoba","Cuenca","Gerona","Granada","Guadalajara","Guipuzcoa","Huelva","Huesca","Jaen","La Coruna","La Rioja","Leon","Leridai","Lugo","Madrid","Malaga","Murcia","Navarra","Orense","Palencia","Las Palmas","Pontevedra","Sala manca","Santa Cruz de Tenerife","Segovia","Sevilla","Soria","Tarragona","Teruel","Toledo","Valencia,Valladolid","Zamora","Zaragoza"] unless const_defined?("GEOGRAPHY_DIVISION_SPAIN_STATES")
        GEOGRAPHY_DIVISION_SRILANKA_STATES=["Central Province","Eastern Province","North Central Province","Northern Province","North Western Province","Sabaragamuwa Province","Southern Province","Uva Province", "Western Province"] unless const_defined?("GEOGRAPHY_DIVISION_SRILANKA_STATES")
        GEOGRAPHY_DIVISION_STBARTHELEMY_STATES=["Anse des Cayes","Grand Cul-de-Sac","Petit Cul-de-Sac","Quartier de Colombier","Quartier de la Grande Saline","Quartier de Public","Quartier de Toiny","Quartier des Flamands","Quartier du Corossol","Quartier du Marigot","Quartier du Roi","Quartier Lorient","Quartier Saint-Jean"] unless const_defined?("GEOGRAPHY_DIVISION_STBARTHELEMY_STATES")
        GEOGRAPHY_DIVISION_STHELENA_STATES=["Alarm Forest","Blue Hill","Half Tree Hollow","Jamestown","Jamestown Harbour","Levelwood","Longwood","Sandy Bay","Saint Paul's"] unless const_defined?("GEOGRAPHY_DIVISION_STHELENA_STATES")
        GEOGRAPHY_DIVISION_STKITTSANDNEVIS_STATES=["Christ Church Nichola Town (Saint Kitts)","Saint Anne Sandy Point (Saint Kitts)","Saint George Basseterre (Saint Kitts)","Saint George Gingerland (Nevis)","Saint James Windward (Nevis)","Saint John Capesterre (Saint Kitts)","Saint John Figtree (Nevis)","Saint Mary Cayon (Saint Kitts)","Saint Paul Capesterre (Saint Kitts)","Saint Paul Charlestown (Nevis)","Saint Peter Basseterre (Saint Kitts)","Saint Thomas Lowland (Nevis)","Saint Thomas Middle Island (Saint Kitts)","Trinity Palmetto Point (Saint Kitts)"] unless const_defined?("GEOGRAPHY_DIVISION_STKITTSANDNEVIS_STATES")
        GEOGRAPHY_DIVISION_STLUCIA_STATES=["Babonneau","Canaries & Anse La Raye","Castries Central","Castries North","Castries North East","Castries South","Castries South East","Choiseul","Dennery North","Dennery South","Gros Islet","Laborie","Micoud North","Micoud South","Soufriere","Vieux Fort North","Vieux Fort South"] unless const_defined?("GEOGRAPHY_DIVISION_STLUCIA_STATES")
        GEOGRAPHY_DIVISION_STMARTIN_STATES=["Saint-Martin(French)","Sint Maarten(Dutch)"] unless const_defined?("GEOGRAPHY_DIVISION_STMARTIN_STATES")
        GEOGRAPHY_DIVISION_STPIERREANDMIQUELON_STATES=["Miquelon-Langlade","Saint-Pierre"] unless const_defined?("GEOGRAPHY_DIVISION_STPIERREANDMIQUELON_STATES")
        GEOGRAPHY_DIVISION_STVINCENTANDTHEGRENADINES_STATES=["Charlotte","Grenadines","Saint Andrew","Saint David","Saint George","Saint Patrick"] unless const_defined?("GEOGRAPHY_DIVISION_STVINCENTANDTHEGRENADINES_STATES")
        GEOGRAPHY_DIVISION_SURINAME_STATES=["Brokopondo","Commewijne","Coronie","Marowijne","Nickerie","Para","Paramaribo","Saramacca","Sipaliwini","Wanica"] unless const_defined?("GEOGRAPHY_DIVISION_SURINAME_STATES")
        GEOGRAPHY_DIVISION_SUDAN_STATES=["Al Jazirah","Al Qadarif","Blue Nile","Central Equatoria","East Equatoria","Junqali","Kassala","Khartoum","Lakes","North Bahr al Ghazal","North Darfur","North Kurdufan","Northern","Red Sea (al-Bahr al-Ahmar)","River Nile","Sennar","South Darfur","South Kurdufan","Unity","Upper Nile","Warab","West Bahr al Ghazal","West Darfur","West Equatoria","White Nile"] unless const_defined?("GEOGRAPHY_DIVISION_SUDAN_STATES")
        GEOGRAPHY_DIVISION_SWAZILAND_STATES=["Hhohho","Lubombo","Manzini","Shiselweni"] unless const_defined?("GEOGRAPHY_DIVISION_SWAZILAND_STATES")
        GEOGRAPHY_DIVISION_SWEDEN_STATES=["Blekinge County","Dalarna County","Gotland County","Gavleborg County","Halland County","Jonkoping County","Jamtland County","Kronoberg County","Kalmar County","Norrbotten County","Orebro County","Ostergotland County","Stockholm County","Sodermanland County","Skane County","Uppsala County","Vasterbotten County","Vastra Gotaland County","Varmland County","Vastmanland County","Vasternorrland County"] unless const_defined?("GEOGRAPHY_DIVISION_SWEDEN_STATES")
        GEOGRAPHY_DIVISION_SWITZERLAND_STATES=["Appenzell Ausserrhoden","Appenzell Innerrhoden","Aargau","Basel-Stadt","Basel-Landschaft. Berne","Fribourg","Glarus","Geneva","Graubunden","Jura","Lucerne","Nidwalden","Neuchatel","Obwalden","Schwyz","Zug","Solothurn","Schaffhausen","St. Gallen","Thurgau","Ticino","Uri","Vaud","Valais","Zurich"] unless const_defined?("GEOGRAPHY_DIVISION_SWITZERLAND_STATES")
        GEOGRAPHY_DIVISION_SYRIA_STATES=["Al-Hasakah Governorate","Aleppo Governorate","Ar-Raqqah Governorate","As-Suwayda Governorate","Daraa Governorate","Deir ez-Zor Governorate","Hama Governorate ","Hims Governorate","Idlib Governorate","Latakia Governorate","Quneitra Governorate","Rif Dimashq","Tartus Governorate"] unless const_defined?("GEOGRAPHY_DIVISION_SYRIA_STATES")
        #T
        GEOGRAPHY_DIVISION_TAIWAN_STATES=["Chiayi","Changhua","Hsinchu","Hualien","Kaohsiung","Miaoli","Nantou","Penghu","Pingtung","Taichung","Tainan","Taipei","Taitung","Taoyuan","Yilan","Yunlin"] unless const_defined?("GEOGRAPHY_DIVISION_TAIWAN_STATES")
        GEOGRAPHY_DIVISION_TAJIKISTAN_STATES=["Khatlon","Gorno-Badakhshan","Sughd","Region of Republican Subordination"] unless const_defined?("GEOGRAPHY_DIVISION_TAJIKISTAN_STATES")
        GEOGRAPHY_DIVISION_TANZANIA_STATES=["Arusha","Dar es Salaam","Dodoma","Iringa","Kagera","Kigoma","Kilimanjaro","Lindi","Manyara","Mara","Mbeya","Morogoro","Mtwara","Mwanza","Pemba North","Pemba South","Pwani","Rukwa","Ruvuma","Shinyanga","Singida","Tabora ","Tanga ","Zanzibar Central/South","Zanzibar North","Zanzibar Urban/West"] unless const_defined?("GEOGRAPHY_DIVISION_TANZANIA_STATES")
        GEOGRAPHY_DIVISION_THAILAND_STATES=["Ang Thong","Amnat Charoen","Bangkok ","Buri Ram","Chumphon","Chaiyaphum","Chiang Mai","Chai Nat","Chiang Rai","Chachoengsao","Chanthaburi","Chonburi","Krabi","Kalasin","Khon Kaen","Kanchanaburi","Kamphaeng Phet","Lampang","Loei","Lamphun","Lopburi","Maha Sarakham","Mukdahan,Mae Hong Son","Nakhon Phanom","Nakhon Ratchasima","Nong Bua Lamphu","Nong Khai","Nakhon Sawan","Nan","Nakhon Si Thammarat","Nakhon Nayok","Narathiwat","Nakhon Pathom","Nonthaburi","Pattani","Phang Nga","Phatthalung","Phuket","Pathum Thani","PrachinburiPhetchaburi","Phayao","Phetchabun","Phichit","Phitsanulok","Phrae","Phra Nakhon Si Ayutthaya","Prachuap Khiri Khan","Ranong","Roi Et","RayongRatchaburi","Sakon Nakhon","Si Sa Ket","Surin","Samut Prkakan","Samut Sakhon","Sukhothai","Satun","Songkhla","Surat Thani","Samut Songkhram","Saraburi","Sing Buri","Suphan Buri","Sa Kaeo","Trang","Trat","Tak","Uthai Thani","Uttaradit","Ubon Ratchakthani","Udon Thani","Yasothon","Yala"]   unless const_defined?("GEOGRAPHY_DIVISION_THAILAND_STATES")
        GEOGRAPHY_DIVISION_TIMORLESTE_STATES=["Aileu","Ainaro","Baucau","Bobonaro","Cova-Lima","Dili","Ermera","Lautem","Liquica","Manatuto","Manufahi","Oecussi-Ambeno","Viqueque"] unless const_defined?("GEOGRAPHY_DIVISION_TIMORLESTE_STATES")
        GEOGRAPHY_DIVISION_TOGO_STATES=["Centrale","Kara","Maritime","Plateaux","Savanes"] unless const_defined?("GEOGRAPHY_DIVISION_TOGO_STATES")
        GEOGRAPHY_DIVISION_TOKELAU_STATES=["Atafu","Nukunonu","Fakaofo"] unless const_defined?("GEOGRAPHY_DIVISION_TOKELAU_STATES")
        GEOGRAPHY_DIVISION_TONGA_STATES=["Haapai","Tongatapu","Vavau"] unless const_defined?("GEOGRAPHY_DIVISION_TONGA_STATES")
        GEOGRAPHY_DIVISION_TRINIDADANDTOBAGO_STATES=["Tobago","Trinidad"] unless const_defined?("GEOGRAPHY_DIVISION_TRINIDADANDTOBAGO_STATES")
        GEOGRAPHY_DIVISION_TUNISIA_STATES=["Ariana","Beja","Ben Arous","Bizerte","Gabes","Gafsa","Jendouba","Kairouan","Kasserine","Kebili Kef","Mahdia","Manouba","Medenine","Monastir","Nabeul","Sfax","Sidi Bou Zid","Siliana","Sousse","Tataouine","Tozeur","Tunis","Zaghouan"] unless const_defined?("GEOGRAPHY_DIVISION_TUNISIA_STATES")
        GEOGRAPHY_DIVISION_TURKEY_STATES=["Aegean Region","Black Sea Region","Central Anatolia Region","Eastern Anatolia Region","Marmara Region","Mediterranean Region","Southeastern Anatolia Region"] unless const_defined?("GEOGRAPHY_DIVISION_TURKEY_STATES")
        GEOGRAPHY_DIVISION_TURKMENISTAN_STATES=["Ahal Province","Balkan Province","Dasoguz Province","Lebap Province","Mary Province"] unless const_defined?("GEOGRAPHY_DIVISION_TURKMENISTAN_STATES")
        GEOGRAPHY_DIVISION_TURKSANDCAICOSISLANDS_STATES=["Grand Turk","Middle Caicos","North Caicos","Providenciales and West Caicos","South Caicos and East Caicos","Salt Cay"] unless const_defined?("GEOGRAPHY_DIVISION_TURKSANDCAICOSISLANDS_STATES")
        GEOGRAPHY_DIVISION_TUVALU_STATES=["Funafuti","Nanumanga","Niulakita","Niutao","Nanumea","Nui","Nukufetau","Nukulaelae","Vaitupu"] unless const_defined?("GEOGRAPHY_DIVISION_TUVALU_STATES")
        #U        
        GEOGRAPHY_DIVISION_UGANDA_STATES=["Abim","Adjumani","Amolatar","Amuru","Apac","Arua","Amuria","Bulisa","Bundibugyo","Bushenyi","Butaleja","Budaka","Bududa","Bugiri","Bukedea","Bukwa","Busia","Dokolo","Gulu","Hoima","Ibanda","Isingiro","Iganga","Jinja","Kabale","Kabarole","Kamwenge","Kanungu","Kasese","Kibale","Kiruhura","Kisoro","Kyenjojo","Kaabong","Kitgum","Koboko","Kotido","Kaberamaido","Kaliro","Kamuli","Kapchorwa","Katakwi","Kumi","Kalangala","Kampala","Kayunga","Kiboga","Luwero","Lyantonde","Lira","Mukono","Manafwa","Mayuge","Mbale","Masaka","Mityana","Mpigi","Mubende","Maracha-Terego","Moroto","Moyo","Masindi","Mbarara","Namutumba","Ntungamo","Nakapiripirit","Nebbi","Nakaseke","Nakasongola","Oyam","Pader","Pallisa","Rakai","Rukungiri","Sironko","Soroti","Tororo Sembabule","Wakiso","Yumbe"] unless const_defined?("GEOGRAPHY_DIVISION_UGANDA_STATES")
        GEOGRAPHY_DIVISION_UKRAINE_STATES=["Cherkasy Oblast","Chernihiv Oblast","Chernivtsi Oblast","Dnipropetrovsk Oblast","Donetsk Oblast","Donetsk Oblast","Ivano-Frankivsk Oblast","Kharkiv Oblast","Kherson Oblast","Kherson Oblast","Khmelnytskyi Oblast","Kiev Oblast","Kirovohrad Oblast","Kirovohrad Oblast","Luhansk Oblast","Lviv Oblast","Mykolaiv Oblast","Mykolaiv Oblast","Odessa Oblast Poltava Oblast","Rivne Oblast","Sumy Oblast","Ternopil Oblast","Vinnytsia Oblast","Volyn Oblast","Zakarpattia Oblast","Zaporizhia Oblast","Zhytomyr Oblast"] unless const_defined?("GEOGRAPHY_DIVISION_UKRAINE_STATES")
        GEOGRAPHY_DIVISION_UNITEDARABEMIRATES_STATES=["Abu Dhabi","Ajman","Dubai","Fujairah","Ras al-Khaimah","Sharjah","Umm al-Quwain"]   unless const_defined?("GEOGRAPHY_DIVISION_UNITEDARABEMIRATES_STATES")
        GEOGRAPHY_DIVISION_UNITEDKINGDOM_STATES = ["Bath and North East Somerset","Bedfordshire","Berkshire","Blackburn with Darwen","Blackpool","Bournemouth","Brighton & Hove","Bristol","Buckinghamshire","Cambridgeshire","Cheshire","Cornwall","Cumbria","Darlington","Derby","Derbyshire","Devon","Dorset","Durham","East Riding of Yorkshire","East Sussex","Essex","Gloucestershire","Greater London","Greater Manchester","Halton","Hampshire","Hartlepool","Herefordshire","Hertfordshire","Hull","Isle of Wight","Kent","Lancashire","Leicester","Leicestershire","Lincolnshire","Luton","Medway","Merseyside","Middlesbrough","Milton Keynes","Norfolk","North East Lincolnshire","North Lincolnshire","North Somerset","North Yorkshire","Northamptonshire","Northumberland","Nottingham","Nottinghamshire","Oxfordshire","Peterborough","Plymouth","Poole","Portsmouth","Redcar and Cleveland","Rutland","Shropshire","Somerset","South Gloucestershire","South Yorkshire","Southampton","Southend-on-Sea","Staffordshire","Stockton-on-Tees","Stoke-on-Trent","Suffolk","Surrey","Swindon","Telford and Wrekin","Thurrock","Torbay","Tyne and Wear","Warrington","Warwickshire","West Midlands","West Sussex","West Yorkshire","Wiltshire","Worcestershire","York","Aberdeen","Aberdeenshire","Angus","Argyll and Bute","Clackmannanshire","Dumfries and Galloway","Dundee","East Ayrshire","East Dunbartonshire","East Lothian","East Renfrewshire","Edinburgh","Falkirk","Fife","Glasgow","Highland","Inverclyde","Midlothian","Moray","North Ayrshire","North Lanarkshire","Orkney","Perth and Kinross","Renfrewshire","Scottish Borders","Shetland","South Ayrshire","South Lanarkshire","Stirling","West Dunbartonshire","West Lothian","Western Isles","Blaenau Gwent","Bridgend","Caerphilly","Cardiff","Carmarthenshire","Ceredigion","Conwy","Denbighshire","Flintshire","Gwynedd","Isle of Anglesey","Merthyr Tydfil","Monmouthshire","Neath Port Talbot","Newport","Pembrokeshire","Powys","Rhondda Cynon Taf","Swansea","Torfaen","Vale of Glamorgan","Wrexham","Antrim","Ards","Armagh","Ballymena","Ballymoney","Banbridge","Belfast","Carrickfergus","Castlereagh","Coleraine","Cookstown","Craigavon","Down","Dungannon and South Tyrone","Fermanagh","Larne","Limavady","Lisburn","Londonderry","Magherafelt","Moyle","Newry and Mourne","Newtownabbey","North Down","Omagh","Strabane"] unless const_defined?("GEOGRAPHY_DIVISION_UNITEDKINGDOM_STATES")
        GEOGRAPHY_DIVISION_UNITEDSTATESMINOROUTLYINGISLANDS_STATES=["BajoNuevo Bank","Baker Island","Howland Island","Jarvis Island","Johnston Atoll","Kingman Reef","Midway Atoll","Palmyra Atoll","Serranilla Bank","Wake Island"] unless const_defined?("GEOGRAPHY_DIVISION_UNITEDSTATESMINOROUTLYINGISLANDS_STATES")
        GEOGRAPHY_DIVISION_UNITEDSTATESOFAMERICA_STATES=["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"] unless const_defined?("GEOGRAPHY_DIVISION_UNITEDSTATESOFAMERICA_STATES")
        GEOGRAPHY_DIVISION_URUGUAY_STATES=["Artigas","Canelones","Cerro Largo","Colonia","Flores","Florida","Lavalleja","Maldonado","Montevideo","Paysandu","Rio Negro","Rivera","Rocha","Salto","San Jose","Tacuarembo","Treinta y Tres"] unless const_defined?("GEOGRAPHY_DIVISION_URUGUAY_STATES")
        GEOGRAPHY_DIVISION_USVIRGINISLANDS_STATES=["St. Croix","St. Thomas","St. John"] unless const_defined?("GEOGRAPHY_DIVISION_USVIRGINISLANDS_STATES")
        GEOGRAPHY_DIVISION_UZBEKISTAN_STATES=["Andijon Viloyati","Buxoro Viloyati","Farg'ona Viloyati","Jizzax Viloyati","Namangan Viloyati","Navoiy Viloyati","Qashqadaryo Viloyati","Qaraqalpaqstan","Respublikasi","Samarqand Viloyati","Sirdaryo Viloyati","Surxondaryo Viloyati","Toshkent Viloyati","Toshkent Shahri","Xorazm Viloyati"] unless const_defined?("GEOGRAPHY_DIVISION_UZBEKISTAN_STATES")
        #V
        GEOGRAPHY_DIVISION_VANUATU_STATES=["Malampa","Penama","Sanma","Shefa","Tafea","Torba"] unless const_defined?("GEOGRAPHY_DIVISION_VANUATU_STATES")
        GEOGRAPHY_DIVISION_VENEZUELA_STATES=["Andean Region","Capital Region","Central Region","Central-Western Region","Guayana Region","Insular Region","Llanos Region","North-Eastern Region","South-Western Region","Zulian Region"] unless const_defined?("GEOGRAPHY_DIVISION_VENEZUELA_STATES")
        GEOGRAPHY_DIVISION_VIETNAM_STATES=["Central Highlands","Greater Ha Noi-Red River Delta","Northwestern","Northeastern","North Central Coast","South Central Coast","Southeastern","Southwestern - Mekong River Delta"] unless const_defined?("GEOGRAPHY_DIVISION_VIETNAM_STATES")
        #W
        GEOGRAPHY_DIVISION_WALLISANDFUTUNAISLANDS_STATES=["Alo","Hahake","Sigave","Uvea"] unless const_defined?("GEOGRAPHY_DIVISION_WALLISANDFUTUNAISLANDS_STATES")
        GEOGRAPHY_DIVISION_WESTERNSAHARA_STATES=["Guelmim-Es Semara","Laayoune-Boujdour-Sakia El Hamra","Oued Ed-Dahab-Lagouira"] unless const_defined?("GEOGRAPHY_DIVISION_WESTERNSAHARA_STATES")
        #X
        #Y
        GEOGRAPHY_DIVISION_YEMEN_STATES=["Adan","Amrank byan","Ad Dali","Al Bayda","Al Hudaydah","Al Jawf","Al Mahrah","Al Mahwit","Amanat Al Asimah","Dhamar","Hadramaut","Hajjah","Ibb","Lahij","Marib","Raymah","Sadah","Sanaa","Shabwah","Taizz"] unless const_defined?("GEOGRAPHY_DIVISION_YEMEN_STATES")
        #Z
        GEOGRAPHY_DIVISION_ZAMBIA_STATES=["Central","Copperbelt","Eastern","Luapula","Lusaka","Northern","North-Western","Western"] unless const_defined?("GEOGRAPHY_DIVISION_ZAMBIA_STATES")
        GEOGRAPHY_DIVISION_ZIMBABWE_STATES=["Bulawayo Metropolitan Province","Harare Metropolitan Province","Manicaland","Mashonaland Central","Mashonaland East","Mashonaland West","Masvingo","Matabeleland North","Matabeleland South","Midland"] unless const_defined?("GEOGRAPHY_DIVISION_ZIMBABWE_STATES")
        
        
      #Gets all the regions based on the conditions supplied in the options
      def get_regions(onlyconditions,excludeconditions)
            sel_region_options = GEOGRAPHY_DIVISION_REGION
              if !onlyconditions.nil? && onlyconditions[:region]
                sel_region_options = onlyconditions[:region].split(",")
              end
              if !excludeconditions.nil? && excludeconditions[:region]
                sel_region_options = GEOGRAPHY_DIVISION_REGION - excludeconditions[:region].split(",")
              end
            return sel_region_options  
        end

      #Gets all the Countries based on the conditions supplied in the options
      def get_countries(onlyconditions, excludeconditions)
           sel_region_options = get_regions(onlyconditions, excludeconditions)      
           sel_countries = Array.new
           for region in sel_region_options
             region = region.gsub(" ","")
             begin
              getcol = eval("GEOGRAPHY_DIVISION_#{region.upcase}_COUNTRIES")
              unless (getcol.nil? || getcol.empty?)
               getcol.each{|country| sel_countries << country}
              end
             rescue
             #do nothing and go to next one
             end
           end
           if !onlyconditions.nil? && onlyconditions[:country]
            sel_countries = onlyconditions[:country].split(",")
           end 
           if !excludeconditions.nil? && excludeconditions[:country]
            sel_countries = sel_countries - excludeconditions[:country].split(",")
           end
           return sel_countries
      end
         
         #Gets all the states based on the conditions supplied in the options
      def get_states(onlyconditions, excludeconditions)
          sel_country_options = get_countries(onlyconditions,excludeconditions)
          sel_states = Array.new
          for country in sel_country_options
           country = country.gsub(" ","")
           country = country.gsub(",","")
           country = country.gsub("'","")
           begin
            getcol = eval("GEOGRAPHY_DIVISION_#{country.upcase}_STATES")
            unless (getcol.nil? || getcol.empty?)
              getcol.each{|state| sel_states << state}
            end
           rescue
             #do nothing and go to next one
             end
           end
           if !onlyconditions.nil? && onlyconditions[:state]
            sel_states = onlyconditions[:state].split(",")
           end 
           if !excludeconditions.nil? && excludeconditions[:state]
            sel_states = sel_states - excludeconditions[:state].split(",")
          end
           return sel_states
        end
    end
  end
end  

